using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.UserAccess;

// <auto-generated />
public class UserCompanyDepartmentMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<UserCompanyDepartment, UserCompanyDepartment>();
    }
}
        