using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Users;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.UserAccess;

// <auto-generated />
public class UserMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<User, User>();
        config.ForType<User, UserOverviewVM>()
            .Map(dest => dest.AssignedWorks, src => src.AssignedWorks);

        config.ForType<User, UserSelectionVM>()
        .Map(dest => dest.StaffId, src => src.StaffId)
        .Map(dest => dest.Role, src => src.Role)
        .Map(dest => dest.FullName, src => src.FullName);
    }
}
