using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;

namespace SWSA.MvcPortal.Services.Interfaces.WorkAssignment;
// <auto-generated />
public interface ICompanyWorkProgressService
{
    // Define your method here
    Task<bool> Edit(EditCompanyWorkProgressRequest req);
}
