using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    Task<int> Create(CreateCompanyWorkAssignmentRequest req);
    Task<CompanyWorkAssignment> Delete(int taskId);
    Task<bool> Edit(EditCompanyWorkAssignmentRequest req);
    Task<CompanyWorkVM> GetWorkAssignmentById(int taskId);

    // Define your method here
    Task<List<CompanyWorkListVM>> GetWorkAssignments();
    Task<List<CompanyWorkCalendarVM>> GetWorkCalendarEvents();
}
