using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Services.Interfaces.WorkAssignment;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    Task<int> Create(CreateCompanyWorkAssignmentRequest req);
    Task<int> RequestWorkAssignment(WorkAssignmentRequest req);

    Task<CompanyWorkAssignment> Delete(int taskId);
    Task<bool> Edit(EditCompanyWorkAssignmentRequest req);
    Task<CompanyWorkAssignment> GetWorkAssignmentById(int taskId);
    Task<T> GetWorkAssignmentById<T>(int taskId) where T : CompanyWorkAssignment;

    // Define your method here
    Task<List<CompanyWorkAssignment>> GetWorkAssignments();
    Task<List<T>> GetWorkAssignments<T>() where T : CompanyWorkAssignment;
    Task<List<CompanyWorkCalendarVM>> GetWorkCalendarEvents();
    Task<bool> UpdateWork<TRequest, TEntity>(TRequest req)
        where TRequest : IWorkAssignmentUpdater<TEntity>
        where TEntity : CompanyWorkAssignment;
}
