using SWSA.MvcPortal.Dtos.Requests.DocumentRecords;
using SWSA.MvcPortal.Models.DocumentRecords;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface IDocumentRecordService
{
    Task<bool> CreateDocument(DocumentRecordRequest doc, IFormFile files);
    Task<bool> CreateDocuments(DocumentRecordListRequest req, List<IFormFile> files);
    Task<bool> Delete(int docId);
    Task<List<DocumentRecordVM>> GetDocumentRecordByCompanyDepartmentId(int companyDepartmentId);
    Task<List<DocumentRecordVM>> GetDocumentRecordByCompanyId(int companyId);
    Task<DocumentRecordVM> GetDocumentRecordById(int id);

    // Define your method here
    Task<List<DocumentRecordVM>> GetDocumentRecords();
}
