using SWSA.MvcPortal.Commons.Quartz.Services.Interfaces;
using Serilog;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Commons.Extensions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Helpers;
using SWSA.MvcPortal.Commons.Quartz.Requests;
using SWSA.MvcPortal.Dtos.Requests.SchedulerJobs;
using SWSA.MvcPortal.Models.ScheduledJobs;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using AutoMapper;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.Auths;
using SWSA.MvcPortal.Services.Interfaces.Systems;
using SWSA.MvcPortal.Persistence;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities.Systems;

namespace SWSA.MvcPortal.Services.Systems;

// <auto-generated />
public class ScheduledJobService(
IMapper mapper,
IUserContext userContext,
IJobSchedulerService schedulerService,
ISystemAuditLogService sysAuditService,
AppDbContext db
) : IScheduledJobService
{
    private readonly DbSet<ScheduledJob> scheduledJobs = db.Set<ScheduledJob>();

    #region Get Data
    public async Task<List<ScheduledJobVM>> GetAllScheduledJobs()
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var data = await scheduledJobs.ToListAsync();
        return mapper.Map<List<ScheduledJobVM>>(data);
    }

    public async Task<ScheduledJobVM> GetScheduledJobByJobKey(string jobKey)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var data = await scheduledJobs.FirstOrDefaultAsync(c => c.JobKey == jobKey);
        Guard.AgainstNullData(data);
        return mapper.Map<ScheduledJobVM>(data);
    }
    #endregion

    public async Task<string> CreateScheduleJob(CreateScheduleJobRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        string cronExpression = CronExpressionBuilder.BuildCronExpression(req.CronFields, req.CronExpression, req.ScheduleType);
        var triggerTime = req.ScheduleType == ScheduleType.Once ? req.TriggerTime : null;

        var request = BaseJobRequest.Create(triggerTime, cronExpression, true);
        var jobKey = await schedulerService.ScheduleJob(request, req.JobType);

        var jobEntity = new ScheduledJob()
        {
            JobKey = jobKey.Name,
            JobGroup = jobKey.Group,
            JobType = req.JobType,
            ScheduleType = req.ScheduleType,
            TriggerTime = triggerTime,
            CronExpression = cronExpression,
            IsEnabled = false,
            IsCustom = true,
            RequestPayloadJson = null, //Default empty , the job must be enalbe at update
            CreatedBy = userContext.Name,
            CreatedAt = DateTime.Now,
            UserId = userContext.EntityId,
        };
        db.Add(jobEntity);
        await db.SaveChangesAsync();
        var log = SystemAuditLogEntry.Create(SystemAuditModule.ScheduleJob, jobEntity.JobKey.ToString(), $"Schedule Job: {jobEntity.JobType.GetDisplayName()}", jobEntity);
        sysAuditService.LogInBackground(log);
        return jobEntity.JobKey;
    }

    public async Task<bool> UpdateScheduleJob(UpdateScheduleJobRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var data = await scheduledJobs.FirstOrDefaultAsync(c => c.JobKey == req.JobKey);
        Guard.AgainstNullData(data, "Job Not Found");
        var oldData = data.DeepClone();

        if (req.ExecuteNow)
        {
            var executeRequest = BaseJobRequest.ExecuteNowRequest();
            await schedulerService.ScheduleJob(executeRequest, data!.JobType);
            data.LastExecuteAt = DateTime.Now;
        }
        string cronExpression = CronExpressionBuilder.BuildCronExpression(req.CronFields, req.CronExpression, req.ScheduleType);
        var triggerTime = req.ScheduleType == ScheduleType.Once ? req.TriggerTime : null;

        data.UpdateInfo(data.IsEnabled, req.ScheduleType, cronExpression, triggerTime);
        var request = BaseJobRequest.Create(triggerTime, cronExpression, data.IsCustom);

        db.Update(data);
        await db.SaveChangesAsync();

        if (data.IsEnabled)
        {
            //If job was enable, require to remove job and trigger - re-schedule
            await schedulerService.ClearSpecificJobByKey(req.JobKey);
            await schedulerService.ScheduleJob(request, data.JobType);
        }
        else
        {
            //Only clear the trigger key, next time enable will re-schedule
            await schedulerService.ClearTriggersByJobkey(req.JobKey);
        }

        var log = SystemAuditLogEntry.Update(SystemAuditModule.ScheduleJob, data.JobKey.ToString(), $"Schedule Job: {data.JobType.GetDisplayName()}", oldData, data);
        sysAuditService.LogInBackground(log);

        return true;
    }

    public async Task<bool> ExecuteByJobKey(string jobKey)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var data = await scheduledJobs.FirstOrDefaultAsync(c => c.JobKey == jobKey);
        Guard.AgainstNullData(data, "Job Not Found");

        var request = new BaseJobRequest()
        {
            StartTime = DateTime.Now,
        };
        await schedulerService.ScheduleJob(request, data.JobType);

        data.LastExecuteAt = DateTime.Now;
        db.Update(data);
        await db.SaveChangesAsync();

        var log = SystemAuditLogEntry.Execute(SystemAuditModule.ScheduleJob, data.JobKey.ToString(), $"Schedule Job: {data.JobType.GetDisplayName()}");
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> DeleteByJobKey(string jobKey)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var data = await scheduledJobs.FirstOrDefaultAsync(c => c.JobKey == jobKey);
        Guard.AgainstNullData(data, "Job Not Found");

        db.Remove(data);
        await db.SaveChangesAsync();

        await schedulerService.ClearSpecificJobByKey(jobKey);

        var log = SystemAuditLogEntry.Delete(SystemAuditModule.CommunicationContact, data.JobKey.ToString(), $"Schedule Job: {data.JobType.GetDisplayName()}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    //For logging use, no need check access permission
    public async Task UpdateExecuteTimeAsync(string jobkey)
    {
        var data = await scheduledJobs.FirstOrDefaultAsync(c => c.JobKey == jobkey);
        if (data == null)
        {
            Log.Error($"[Job] job key not found, update failed :{jobkey}");
            return;
        }

        data.LastExecuteAt = DateTime.Now;
        db.Update(data);
        await db.SaveChangesAsync();
    }

}