using SWSA.MvcPortal.Services.Interfaces.Systems;
using SWSA.MvcPortal.Persistence;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Commons.Services.Messaging.Models;
using SWSA.MvcPortal.Entities.Systems;

namespace SWSA.MvcPortal.Services.Systems;

// <auto-generated />
public class SystemNotificationLogService(
    AppDbContext db
    ) : ISystemNotificationLogService
{
    private readonly DbSet<SystemNotificationLog> notificationLogs = db.Set<SystemNotificationLog>();

    #region VM/DTO Query Method 
    public async Task<List<SystemNotificationLog>> GetLogs()
    {
        var data = await notificationLogs.ToListAsync();
        return [.. data];
    }
    #endregion

    public async Task AddLog(MessagingResult result)
    {
        var log = new SystemNotificationLog
        {
            Channel = result.Channel,
            Recipient = result.Recipient,
            IsSuccess = result.IsSuccess,
            ResultMessage = result.Message,
        };

        db.Add(log);
        await db.SaveChangesAsync();
    }
}