using Mapster;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

// <auto-generated />
public class AnnualReturnSubmissionRepository(AppDbContext _db) : RepositoryBase<AnnualReturnSubmission>(_db), IAnnualReturnSubmissionRepository
{
    private IQueryable<AnnualReturnSubmission> BaseQuery(bool asNoTracking = false)
    {
        var query = _db.Set<AnnualReturnSubmission>();
        return asNoTracking ? query.AsNoTracking() : query;
    }
    // Implement the method
    #region VM Method
    public async Task<List<AnnualReturnSubmissionVM>> GetListVMAsync()
    {
        var dtos = await BaseQuery(true)
             .ProjectToType<AnnualReturnSubmissionVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<AnnualReturnSubmissionVM> GetVMByIdAsync(int id)
    {
        var dtos = await BaseQuery(true)
             .Where(c => c.Id == id)
             .ProjectToType<AnnualReturnSubmissionVM>()
             .FirstOrDefaultAsync();

        return dtos!;
    }
    #endregion
    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<AnnualReturnSubmission>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(_db.Set<AnnualReturnSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<AnnualReturnSubmission>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<AnnualReturnSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

     //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<AnnualReturnSubmission>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<AnnualReturnSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(AnnualReturnSubmission entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(AnnualReturnSubmission entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(AnnualReturnSubmission entity)
    {
        //Do you logic here
    }
}