using Mapster;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

// <auto-generated />
public class AuditSubmissionRepository(AppDbContext _db) : RepositoryBase<AuditSubmission>(_db), IAuditSubmissionRepository
{
    private IQueryable<AuditSubmission> BaseQuery(bool asNoTracking = false)
    {
        var query = _db.Set<AuditSubmission>();
        return asNoTracking ? query.AsNoTracking() : query;
    }
    // Implement the method
    #region VM Method
    public async Task<List<AuditSubmissionVM>> GetListVMAsync()
    {
        var dtos = await BaseQuery(true)
             .ProjectToType<AuditSubmissionVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<AuditSubmissionVM> GetVMByIdAsync(int id)
    {
        var dtos = await BaseQuery(true)
             .Where(c => c.Id == id)
             .ProjectToType<AuditSubmissionVM>()
             .FirstOrDefaultAsync();

        return dtos!;
    }

    #endregion
    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<AuditSubmission>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(_db.Set<AuditSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<AuditSubmission>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<AuditSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

     //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<AuditSubmission>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<AuditSubmission>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(AuditSubmission entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(AuditSubmission entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(AuditSubmission entity)
    {
        //Do you logic here
    }
}