// <auto-generated />

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyCommunicationContactRepository(AppDbContext db) : RepositoryBase<CompanyCommunicationContact>(db), ICompanyCommunicationContactRepository
{
  
    // Implement the method

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyCommunicationContact>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<CompanyCommunicationContact>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyCommunicationContact>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyCommunicationContact>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override void BeforeRemove(CompanyCommunicationContact entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override void BeforeAdd(CompanyCommunicationContact entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override void BeforeUpdate(CompanyCommunicationContact entity)
    {
        //Do you logic here
    }
}
