// <auto-generated />

using System.Threading.Tasks;
using Mapster;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Companies;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyRepository(AppDbContext db) : RepositoryBase<Company>(db), ICompanyRepository
{
    private IQueryable<Company> ActiveCompanies(bool asNoTracking = false)
    {
        var query = db.Set<Company>().Where(c => !c.IsDeleted);
        return asNoTracking ? query.AsNoTracking() : query;
    }
    // Implement the method

    #region VM Method
    public async Task<List<CompanyListVM>> GetListVMAsync()
    {
        var dtos = await ActiveCompanies(true)
             .ProjectToType<CompanyListVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<List<CompanyListVM>> GetListVMByTypeAsync(CompanyType type)
    {
        var dtos = await ActiveCompanies(true)
             .Where(c => c.CompanyType == type)
             .ProjectToType<CompanyListVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<List<CompanyListVM>> GetListVMByUserIdAsync(int userId)
    {
        var dtos = await ActiveCompanies(true)
             .Where(c => c.UserCompanyDepartments
             .Any(ucd => ucd.UserId == userId))
             .ProjectToType<CompanyListVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<List<CompanyListVM>> GetListVMByUserIdAndTypeAsync(int userId, CompanyType type)
    {
        var dtos = await ActiveCompanies(true)
             .Where(c => c.UserCompanyDepartments
             .Any(ucd => ucd.UserId == userId) &&
                         c.CompanyType == type)
             .ProjectToType<CompanyListVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<List<CompanySelectionVM>> GetSelectionsVMAsync()
    {
        var dtos = await ActiveCompanies(true)
             .ProjectToType<CompanySelectionVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<List<CompanySelectionVM>> GetSelectionsVMByUserIdAsync(int userId)
    {
        var dtos = await ActiveCompanies(true)
            .Where(c => c.UserCompanyDepartments
            .Any(ucd => ucd.UserId == userId))
             .ProjectToType<CompanySelectionVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<CompanySecretaryVM> GetSecretaryVMByIdAsync(int id)
    {
        var dtos = await ActiveCompanies(true)
            .Where(c => c.Id == id)
            .ProjectToType<CompanySecretaryVM>()
            .FirstOrDefaultAsync();
        return dtos;
    }

    public async Task<CompanySimpleInfoVM> GetSimpleInfoVMByIdAsync(int id)
    {
        var dtos = await ActiveCompanies(true)
            .Where(c => c.Id == id)
            .ProjectToType<CompanySimpleInfoVM>()
            .FirstOrDefaultAsync();
        return dtos;
    }
    #endregion

    public async Task<List<Company>> GetCompaniesByIdsAsync(List<int> companyIds)
    {
        var query = await BuildQueryAsync();

        if (companyIds.Count == 1)
        {
            var companyId = companyIds.First();
            return await query.Where(c => c.Id == companyId).ToListAsync();
        }

        return await query.Where(c => companyIds.Contains(c.Id)).ToListAsync();
    }

    public async Task<List<Company>> GetCompaniesByUserId(int userId)
    {
        var query = await BuildQueryAsync();

        return await query
            .Where(c => c.UserCompanyDepartments
            .Any(ucd => ucd.UserId == userId))
            .ToListAsync();
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<Company>> BuildQueryAsync()
    {
        var query = ActiveCompanies();

        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<Company>> BuildQueryWithIncludesAsync()
    {
        var query = ActiveCompanies()
            .Include(c => c.ComplianceDate)
            .Include(c => c.Owners)
            .Include(c => c.OfficialContacts)
            .Include(c => c.CommunicationContacts)
            .Include(c => c.UserCompanyDepartments).ThenInclude(u => u.User)
            .Include(c => c.MsicCodes).ThenInclude(cm => cm.MsicCode)
            .Include(c => c.WorkAssignments).ThenInclude(c => c.AccountPlannedMonths)
            .Include(c => c.WorkAssignments).ThenInclude(c => c.AuditPlannedMonths)
            .Include(c => c.WorkAssignments).ThenInclude(c => c.AssignedUsers)
            .Include(c => c.WorkAssignments).ThenInclude(c => c.Progress)
            .Include(c => c.WorkAssignments).ThenInclude(c => c.Submission)
            .Where(c => !c.IsDeleted);

        return Task.FromResult(query);
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<Company>> BuildGetByIdQueryAsync()
    {
        var query = db.Companies
            .Where(c => !c.IsDeleted);

        return Task.FromResult(query);
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(Company entity)
    {
        //Do you logic here
        var findContacts = await db.CompanyCommunicationContact
            .Where(c => c.CompanyId == entity.Id)
            .ToListAsync();
        var findComplianceDate = await db.CompanyComplianceDates.Where(c => c.CompanyId == entity.Id)
            .ToListAsync();

        if (findContacts.Count > 0)
        {
            db.CompanyCommunicationContact.RemoveRange(findContacts);
        }
        if (findComplianceDate.Count > 0)
        {
            db.CompanyComplianceDates.RemoveRange(findComplianceDate);
        }

    }
    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(Company entity)
    {
        //Do you logic here
    }
    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(Company entity)
    {
        //Do you logic here
    }


}

