
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

// <auto-generated />
public class CompanyComplianceDateRepository(AppDbContext db) : RepositoryBase<CompanyComplianceDate>(db), ICompanyComplianceDateRepository
{
  
    // Implement the method

    public async Task<CompanyComplianceDate> GetByCompanyId(int companyId)
    {
      return await db.CompanyComplianceDates.FirstOrDefaultAsync(c=>c.CompanyId == companyId);
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyComplianceDate>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<CompanyComplianceDate>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyComplianceDate>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyComplianceDate>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CompanyComplianceDate entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CompanyComplianceDate entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CompanyComplianceDate entity)
    {
        //Do you logic here
    }
}
