
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

// <auto-generated />
public class CompanyDepartmentRepository(AppDbContext db) : RepositoryBase<CompanyDepartment>(db), ICompanyDepartmentRepository
{

    // Implement the method
    public async Task<List<CompanyDepartment>> GetByIdsAsync(List<int> ids)
    {
        var query = await BuildQueryAsync();
        if (ids.Count == 1)
        {
            var id = ids.First();
            return await query.Where(x => x.Id == id).ToListAsync();
        }
        return await query.Where(x => ids.Contains(x.Id)).ToListAsync();
    }

    public async Task<List<CompanyDepartment>> GetByCompanyId(int companyId)
    {
        var query = await BuildQueryAsync();
        return await query
            .Where(x => x.CompanyId == companyId)
            .ToListAsync();
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyDepartment>> BuildQueryAsync()
    {
        var query = db.Set<CompanyDepartment>()
            .Include(x => x.Company)
            .Include(x => x.CompanyStaffs)
            .Include(x => x.Department)
            .AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyDepartment>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyDepartment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CompanyDepartment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CompanyDepartment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CompanyDepartment entity)
    {
        //Do you logic here
    }
}
