// <auto-generated />

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyOwnerRepository(AppDbContext db) : RepositoryBase<CompanyOwner>(db), ICompanyOwnerRepository
{
  
    // Implement the method

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyOwner>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<CompanyOwner>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyOwner>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyOwner>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override void BeforeRemove(CompanyOwner entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override void BeforeAdd(CompanyOwner entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override void BeforeUpdate(CompanyOwner entity)
    {
        //Do you logic here
    }
}
