// <auto-generated />

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyMsicCodeRepository(AppDbContext db) : RepositoryBase<CompanyMsicCode>(db), ICompanyMsicCodeRepository
{
  
    // Implement the method

    public async Task<List<CompanyMsicCode>> GetByCompanyId(int companyId)
    {
        var data = db.CompanyMsicCodes.Where(c => c.CompanyId == companyId);
        return await data.ToListAsync();
    }

    public async Task<List<CompanyMsicCode>> GetByIdsAsync(List<int> msicCodeIds)
    {
        var data = db.CompanyMsicCodes.Where(c => msicCodeIds.Contains(c.MsicCodeId));
        return await data.ToListAsync();
    }


    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyMsicCode>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<CompanyMsicCode>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyMsicCode>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyMsicCode>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override void BeforeRemove(CompanyMsicCode entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override void BeforeAdd(CompanyMsicCode entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override void BeforeUpdate(CompanyMsicCode entity)
    {
        //Do you logic here
    }
}
