

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class CompanyStaffRepository(AppDbContext db) : RepositoryBase<CompanyStaff>(db), ICompanyStaffRepository
{

    // Implement the method
    public async Task<CompanyStaff> GetByStaffId(string staffId)
    {
        var find = await db.CompanyStaffs
            .Include(c => c.CompanyDepartment)
            .ThenInclude(c => c.Department)
            .Include(c => c.Company)
            .FirstOrDefaultAsync(c => c.StaffId == staffId);
        return find!;
    }

    public async Task<bool> ExistUsernameInCompanyExcludingStaffId(int companyId, string username,string excludeStaffId)
    {
        return await db.CompanyStaffs
            .AnyAsync(c => c.CompanyId == companyId && c.Username == username && c.StaffId != excludeStaffId);
    }

    public async Task<List<CompanyStaff>> GetAllByCompanyIdAsync(int companyId)
    {
        var data = await db.CompanyStaffs
            .Include(c => c.CompanyDepartment)
            .ThenInclude(c => c.Department)
            .Where(c => c.CompanyId == companyId).ToListAsync();
        return data;
    }


    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyStaff>> BuildQueryAsync()
    {
        // Do you query here
        var query = db.CompanyStaffs
           .Include(c => c.CompanyDepartment)
           .ThenInclude(c => c.Department)
           .Include(c => c.Company)
           .AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyStaff>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyStaff>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<CompanyStaff>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyStaff>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CompanyStaff entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CompanyStaff entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CompanyStaff entity)
    {
        //Do you logic here
    }
}
