// <auto-generated />

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyRepository(AppDbContext db) : RepositoryBase<Company>(db), ICompanyRepository
{
    // Implement the method
  

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<Company>> BuildQueryAsync()
    {

        var query = db.Companies
            .Include(c => c.CompanyType)
            .Include(c => c.CompanyComplianceDate)
            .Include(c => c.CompanyOwners)
            .Include(c => c.CommunicationContacts)
            .Include(c => c.OfficialContacts)
            .Include(c => c.MsicCodes).ThenInclude(cm => cm.MsicCode)
            .Include(c => c.Departments).ThenInclude(cd => cd.Department)
            .Include(c => c.Departments).ThenInclude(cd => cd.CommunicationContacts)
            .AsNoTracking();

        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<Company>> BuildQueryWithIncludesAsync()
    {
        var query = db.Companies
            .Include(c => c.CompanyType)
            .Include(c => c.CompanyComplianceDate)
            .Include(c => c.CompanyOwners)
            .Include(c => c.CommunicationContacts)
            .Include(c => c.OfficialContacts)
            .Include(c => c.MsicCodes).ThenInclude(cm => cm.MsicCode)
            .Include(c => c.Departments).ThenInclude(cd => cd.Department)
            .Include(c => c.Departments).ThenInclude(cd => cd.CommunicationContacts)
            .AsNoTracking();

        return Task.FromResult(query);
    }

    //Add the method that want to perform before delete the entity
    protected override void BeforeRemove(Company entity)
    {
        //Do you logic here
    }
    //Add the method that want to perform before add the entity
    protected override void BeforeAdd(Company entity)
    {
        //Do you logic here
    }
    //Add the method that want to perform before update the entity
    protected override void BeforeUpdate(Company entity)
    {
        //Do you logic here
    }


}

