

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class CompanyWorkAssignmentRepository(AppDbContext db) : RepositoryBase<CompanyWorkAssignment>(db), ICompanyWorkAssignmentRepository
{

    // Implement the method

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyWorkAssignment>> BuildQueryAsync()
    {
        // Do you query here
        var query = db.CompanyWorkAssignments
                  .Include(c => c.Progress) 
                  .Include(c => c.Company)
                  .Include(c => c.AssignedStaff)
                      .ThenInclude(s => s.CompanyDepartment)
                      .ThenInclude(cd => cd.Department)
                  .AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyWorkAssignment>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyWorkAssignment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<CompanyWorkAssignment>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyWorkAssignment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CompanyWorkAssignment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CompanyWorkAssignment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CompanyWorkAssignment entity)
    {
        //Do you logic here
    }
}
