// <auto-generated />

using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyRepository(AppDbContext db) : RepositoryBase<Company>(db), ICompanyRepository
{
    // Implement the method
    public async Task<List<Company>> GetCompaniesByIdsAsync(List<int> companyIds)
    {
        var query = await BuildQueryAsync();

        if (companyIds.Count == 1)
        {
            var companyId = companyIds.First();
            return await query.Where(c => c.Id == companyId).ToListAsync();
        }

        return await query.Where(c => companyIds.Contains(c.Id)).ToListAsync();
    }

    public async Task<List<Company>> GetCompaniesByUserId(int userId)
    {
        var query = await BuildQueryAsync();

        return await query.Include(c => c.UserCompanyDepartments)
            .Where(c => c.UserCompanyDepartments
            .Any(ucd => ucd.UserId == userId))
            .ToListAsync();
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<Company>> BuildQueryAsync()
    {
        var query = db.Companies
                 .Include(c => c.CompanyComplianceDate)
                 .Include(c => c.CompanyOwners)
                 .Include(c => c.OfficialContacts)
                 .Include(c => c.CompanyStaffs)
                 .Include(c => c.UserCompanyDepartments).ThenInclude(u => u.User)
                 .Include(c => c.MsicCodes).ThenInclude(cm => cm.MsicCode)
                 .Include(c => c.Departments).ThenInclude(cd => cd.Department)
                 .Where(c => !c.IsDeleted)
                 .AsNoTracking();

        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<Company>> BuildQueryWithIncludesAsync()
    {
        var query = db.Companies
            .Include(c => c.CompanyComplianceDate)
            .Include(c => c.CompanyOwners)
            .Include(c => c.OfficialContacts)
            .Include(c => c.CompanyStaffs)
            .Include(c => c.UserCompanyDepartments).ThenInclude(u=>u.User)
            .Include(c => c.MsicCodes).ThenInclude(cm => cm.MsicCode)
            .Include(c => c.Departments).ThenInclude(cd => cd.Department)
            .Where(c => !c.IsDeleted);

        return Task.FromResult(query);
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<Company>> BuildGetByIdQueryAsync()
    {
        var query = db.Companies
            .Where(c => !c.IsDeleted);

        return Task.FromResult(query);
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(Company entity)
    {
        //Do you logic here
        var findContacts = await db.CompanyStaffs
            .Where(c => c.CompanyId == entity.Id)
            .ToListAsync();
        var findComplianceDate = await db.CompanyComplianceDates.Where(c => c.CompanyId == entity.Id)
            .ToListAsync();

        if (findContacts.Count > 0)
        {
            db.CompanyStaffs.RemoveRange(findContacts);
        }
        if (findComplianceDate.Count > 0)
        {
            db.CompanyComplianceDates.RemoveRange(findComplianceDate);
        }

    }
    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(Company entity)
    {
        //Do you logic here
    }
    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(Company entity)
    {
        //Do you logic here
    }


}

