// <auto-generated />
using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Repo;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyOwnerRepository(AppDbContext db) : RepositoryBase<CompanyOwner>(db), ICompanyOwnerRepository
{
  
    // Implement the method
}

