

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class CompanyCommunicationContactRepository(AppDbContext db) : RepositoryBase<CommunicationContact>(db), ICompanyCommunicationContactRepository
{

    // Implement the method

    public async Task<List<CommunicationContact>> GetAllByCompanyIdAsync(int companyId)
    {
        var data = await db.CompanyCommunicationContact
            .Where(c => c.CompanyId == companyId).ToListAsync();
        return data;
    }


    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CommunicationContact>> BuildQueryAsync()
    {
        // Do you query here
        var query = db.CompanyCommunicationContact
           .Include(c => c.Company)
           .AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CommunicationContact>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CommunicationContact>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<CommunicationContact>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CommunicationContact>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CommunicationContact entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CommunicationContact entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CommunicationContact entity)
    {
        //Do you logic here
    }
}
