// <auto-generated />
using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Repo;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class CompanyDepartmentRepository(AppDbContext db) : RepositoryBase<CompanyDepartment>(db), ICompanyDepartmentRepository
{
  
    // Implement the method
}

