using Mapster;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class CompanyStrikeOffSubmissionRepository(AppDbContext db) : RepositoryBase<CompanyStrikeOffSubmission>(db), ICompanyStrikeOffSubmissionRepository
{
    private IQueryable<CompanyStrikeOffSubmission> BaseQuery(bool asNoTracking = false)
    {
        var query = db.Set<CompanyStrikeOffSubmission>();
        return asNoTracking ? query.AsNoTracking() : query;
    }
    // Implement the method
    #region VM Method
    public async Task<List<CompanyStrikeOffSubmissionVM>> GetListVMAsync()
    {
        var dtos = await BaseQuery(true)
             .ProjectToType<CompanyStrikeOffSubmissionVM>()
             .ToListAsync();

        return dtos;
    }

    public async Task<CompanyStrikeOffSubmissionVM> GetVMByIdAsync(int id)
    {
        var dtos = await BaseQuery(true)
             .Where(c => c.Id == id)
             .ProjectToType<CompanyStrikeOffSubmissionVM>()
             .FirstOrDefaultAsync();

        return dtos!;
    }
    #endregion

    public async Task<CompanyStrikeOffSubmission> GetByCompanyId(int companyId)
    {
        var query = await BuildQueryAsync();
        var data = await query.FirstOrDefaultAsync(x => x.CompanyId == companyId);
        return data!;
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<CompanyStrikeOffSubmission>> BuildQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyStrikeOffSubmission>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<CompanyStrikeOffSubmission>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyStrikeOffSubmission>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<CompanyStrikeOffSubmission>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<CompanyStrikeOffSubmission>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(CompanyStrikeOffSubmission entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(CompanyStrikeOffSubmission entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(CompanyStrikeOffSubmission entity)
    {
        //Do you logic here
    }
}
