

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class DepartmentRepository(AppDbContext db) : RepositoryBase<Department>(db), IDepartmentRepository
{

    // Implement the method
    public async Task<List<Department>> GetByIdsAsync(List<int> dpIds)
    {
        var data = db.Departments.Where(c => dpIds.Contains(c.Id));
        return await data.ToListAsync();
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<Department>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<Department>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<Department>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<Department>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

     //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<Department>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<Department>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(Department entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(Department entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(Department entity)
    {
        //Do you logic here
    }


}
