// <auto-generated />

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;
using System.ComponentModel.Design;

namespace SWSA.MvcPortal.Repositories.Repo;

public class DocumentRecordRepository(AppDbContext db) : RepositoryBase<DocumentRecord>(db), IDocumentRecordRepository
{

    // Implement the method
    public async Task<List<DocumentRecord>> GetDocumentRecordsByCompanyId(int companyId)
    {
        var data = await db.DocumentRecords
                .AsNoTracking()
                .Include(c => c.Department) //For company department
                .ThenInclude(c => c.Department) //Public setting
                .Include(c => c.Department) 
                .ThenInclude(c => c.Company) 
                .Include(c => c.HandledByStaff) //For staff
                .Where(c => c.Department != null && !c.Department.Company.IsDeleted && c.Department.CompanyId == companyId)
                .ToListAsync();
        return data;
    }

    public async Task<List<DocumentRecord>> GetDocumentRecordsByCompanyDepartmentId(int companyDepartmentId)
    {
        var data = await db.DocumentRecords
          .AsNoTracking()
          .Include(c => c.Department) //For company department
          .ThenInclude(c => c.Department) //Public setting
          .Include(c => c.Department)
          .ThenInclude(c => c.Company)
          .Include(c => c.HandledByStaff) //For staff
          .Where(c => c.CompanyDepartmentId == companyDepartmentId && c.Department != null && !c.Department.Company.IsDeleted)
          .ToListAsync();
        return data;
    }

    public async Task<List<DocumentRecord>> GetDocumentRecordsByStaffId(string staffId)
    {
        var data = await db.DocumentRecords
            .AsNoTracking()
            .Include(c => c.HandledByStaff)
            .Include(c => c.Department)
            .ThenInclude(c => c.Company) 
            .Where(c => c.HandledByStaff != null && c.HandledByStaff.StaffId == staffId 
                     && c.Department != null && !c.Department.Company.IsDeleted)
            .ToListAsync();

        return data;
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<DocumentRecord>> BuildQueryAsync()
    {
        //Default query no action
        //return Task.FromResult(db.Set<DocumentRecord>().AsQueryable());

        // Do you query here
        var query = db.DocumentRecords
                .Include(c => c.Department) //For company department
                .ThenInclude(c => c.Department) //Public setting
                .Include(c => c.Department)
                .ThenInclude(c => c.Company)
                .Include(c => c.HandledByStaff) //For staff
                .Where(c => c.Department != null && !c.Department.Company.IsDeleted)
                .AsNoTracking();
        //For staff;
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<DocumentRecord>> BuildQueryWithIncludesAsync()
    {
        // Do you query here
        var query = db.DocumentRecords
                .Include(c => c.Department) //For company department
                .ThenInclude(c => c.Department) //Public setting
                .Include(c => c.Department)
                .ThenInclude(c => c.Company)
                .Include(c => c.HandledByStaff) //For staff
                .Where(c => c.Department != null && !c.Department.Company.IsDeleted)
                .AsNoTracking();
        //For staff;
        return Task.FromResult(query);
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(DocumentRecord entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(DocumentRecord entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(DocumentRecord entity)
    {
        //Do you logic here
    }
}
