

using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class ScheduledJobRepository(AppDbContext db) : RepositoryBase<ScheduledJob>(db), IScheduledJobRepository
{
    // Implement the method
    public async Task<List<ScheduledJob>> GetDefaultAndEnabledJobs()
    {

        return await db.Set<ScheduledJob>().Where(c => !c.IsCustom).ToListAsync();
    }

    public async Task<ScheduledJob> GetScheduledByJobKeyAsync(string jobkey)
    {
        var find = await db.Set<ScheduledJob>()
                .FirstOrDefaultAsync(c => c.JobKey == jobkey);
        return find!;
    }
    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<ScheduledJob>> BuildQueryAsync()
    {
        // Do you query here
        var query = db.Set<ScheduledJob>().Include(c => c.User).AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<ScheduledJob>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<ScheduledJob>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<ScheduledJob>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<ScheduledJob>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(ScheduledJob entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(ScheduledJob entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(ScheduledJob entity)
    {
        //Do you logic here
    }
}
