using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class SystemAuditLogRepository(AppDbContext db) : RepositoryBase<SystemAuditLog>(db), ISystemAuditLogRepository
{

    // Implement the method
    public async Task<string> GetChangeSumamryJsonById(int id)
    {
        var data = await db.Set<SystemAuditLog>().Where(c => c.Id == id).Select(c => c.ChangeSummaryJson).FirstOrDefaultAsync();
        return data!;
    }


    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<SystemAuditLog>> BuildQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<SystemAuditLog>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<SystemAuditLog>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<SystemAuditLog>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<SystemAuditLog>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<SystemAuditLog>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(SystemAuditLog entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(SystemAuditLog entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(SystemAuditLog entity)
    {
        //Do you logic here
    }
}
