using System.ComponentModel.Design;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class UserCompanyDepartmentRepository(AppDbContext db) : RepositoryBase<UserCompanyDepartment>(db), IUserCompanyDepartmentRepository
{

    // Implement the method
    public async Task<List<UserCompanyDepartment>> GetByCompanyIdAndStaffId(int companyId, string staffId)
    {
        var query = await BuildQueryAsync();
        return await query.Where(x => x.CompanyId == companyId && x.User.StaffId == staffId).ToListAsync();
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<UserCompanyDepartment>> BuildQueryAsync()
    {
        var query = db.Set<UserCompanyDepartment>()
           .Include(c => c.User)
           .Include(c => c.Department)
           .AsNoTracking();
        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<UserCompanyDepartment>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<UserCompanyDepartment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<UserCompanyDepartment>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<UserCompanyDepartment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(UserCompanyDepartment entity)
    {
        entity.User = null!;
        entity.Department = null!;
        entity.Company = null!;
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(UserCompanyDepartment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(UserCompanyDepartment entity)
    {
        //Do you logic here
    }
}
