// <auto-generated />
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace SWSA.MvcPortal.Repositories.Repo;

public class UserRepository(AppDbContext db) : RepositoryBase<User>(db), IUserRepository
{

    // Implement the method
    public async Task<List<User>> GetUserByCompanyId(int companyId)
    {
        var query = await BuildQueryAsync();
        return await query.Where(u => u.CompanyDepartments != null
        && u.CompanyDepartments.Any(c => c.CompanyId == companyId)).ToListAsync();
    }

    public async Task<List<User>> GetByActiveStatus(bool isActive)
    {
        var query = await BuildQueryAsync();
        return await query.Where(u => u.IsActive == isActive).ToListAsync();
    }

    public async Task<User> GetByUsernameAsync(string username)
    {
        var query = await BuildQueryAsync();
        return await query.FirstOrDefaultAsync(u => u.Username == username);
    }

    public async Task<User> GetByStaffIdAsync(string staffId)
    {
        var query = await BuildQueryAsync();
        return await query.FirstOrDefaultAsync(u => u.StaffId == staffId);
    }

    public async Task<User> GetOverviewByStaffIdAsync(string staffId)
    {
        var query = await BuildQueryAsync();
        query = query.Include(c => c.SystemAuditLogs)
                     .Include(c => c.CompanyDepartments).ThenInclude(c => c.Company);
        return await query.FirstOrDefaultAsync(u => u.StaffId == staffId);
    }

    public async Task<Dictionary<string, int>> GetDictionaryIdByStaffIdsAsync(List<string> staffIds)
    {
        if (staffIds == null || !staffIds.Any())
            return new Dictionary<string, int>();

        var query = await BuildQueryAsync();
        return await query
            .Where(u => staffIds.Contains(u.StaffId))
            .ToDictionaryAsync(u => u.StaffId, u => u.Id);
    }

    public async Task<Dictionary<string, User>> GetDictionaryByStaffIdsAsync(List<string> staffIds)
    {
        if (staffIds == null || !staffIds.Any())
            return new Dictionary<string, User>();

        var query = await BuildQueryAsync();
        return await query.Where(u => staffIds.Contains(u.StaffId))
                          .ToDictionaryAsync(u => u.StaffId);
    }

    public async Task<bool> ExistsByUsernameAsync(string username)
    {
        return await db.Set<User>().AnyAsync(u => u.Username == username);
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<User>> BuildQueryAsync()
    {
        var query = db.Set<User>()
           .Include(c => c.CompanyDepartments)
           .AsNoTracking();
        return Task.FromResult(query);
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(User entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(User entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(User entity)
    {
        //Do you logic here
    }
}

