// <auto-generated />
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

public class UserRepository(AppDbContext db) : RepositoryBase<User>(db), IUserRepository
{

    // Implement the method
    public async Task<User> GetByUsernameAsync(string username)
    {
        return await db.Users.FirstOrDefaultAsync(u => u.Username == username);
    }

    public async Task<User> GetByStaffIdAsync(string staffId)
    {
        return await db.Users.FirstOrDefaultAsync(u => u.StaffId == staffId);
    }

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<User>> BuildQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<User>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override void BeforeRemove(User entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override void BeforeAdd(User entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override void BeforeUpdate(User entity)
    {
        //Do you logic here
    }
}

