using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class WorkAssignmentAuditMonthRepository(AppDbContext db) : RepositoryBase<WorkAssignmentAuditMonth>(db), IWorkAssignmentAuditMonthRepository
{
  
    // Implement the method

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<WorkAssignmentAuditMonth>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentAuditMonth>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<WorkAssignmentAuditMonth>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentAuditMonth>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

     //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<WorkAssignmentAuditMonth>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentAuditMonth>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(WorkAssignmentAuditMonth entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(WorkAssignmentAuditMonth entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(WorkAssignmentAuditMonth entity)
    {
        //Do you logic here
    }
}
