using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;

// <auto-generated />
public class WorkProgressRepository(AppDbContext _db) : RepositoryBase<WorkProgress>(_db), IWorkProgressRepository
{
    private IQueryable<WorkProgress> BaseQuery(bool asNoTracking = false)
    {
        var query = _db.Set<WorkProgress>();
        return asNoTracking ? query.AsNoTracking() : query;
    }  
    // Implement the method
    #region VM Method
    #endregion
    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<WorkProgress>> BuildQueryAsync()
    {
       //Default query no action
        return Task.FromResult(_db.Set<WorkProgress>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
     }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<WorkProgress>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<WorkProgress>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

     //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<WorkProgress>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(_db.Set<WorkProgress>().AsQueryable());

        // Do you query here
        // var query = _db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(WorkProgress entity)
    {
    //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(WorkProgress entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(WorkProgress entity)
    {
        //Do you logic here
    }
}