using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class WorkAssignmentUserMappingRepository(AppDbContext db) : RepositoryBase<WorkAssignmentUserMapping>(db), IWorkAssignmentUserMappingRepository
{

    // Implement the method
    public async Task<WorkAssignmentUserMapping?> GetByUserIdAsync(int taskId, int userId, string department)
    {
        var query = db.Set<WorkAssignmentUserMapping>().FirstOrDefaultAsync(c =>
        c.WorkAssignmentId == taskId &&
        c.UserId == userId &&
        c.Department == department);
        return await query;
    }
    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<WorkAssignmentUserMapping>> BuildQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentUserMapping>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<WorkAssignmentUserMapping>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentUserMapping>().AsQueryable());

        // Do you query here
        // var query = db.TableNames.AsNoTracking();
        // return Task.FromResult(query);    
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<WorkAssignmentUserMapping>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignmentUserMapping>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(WorkAssignmentUserMapping entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(WorkAssignmentUserMapping entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(WorkAssignmentUserMapping entity)
    {
        //Do you logic here
    }
}
