using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Repo;
// <auto-generated />
public class WorkAssignmentRepository(AppDbContext db) : RepositoryBase<WorkAssignment>(db), IWorkAssignmentRepository
{
    private IQueryable<WorkAssignment> BaseQuery(bool asNoTracking = false)
    {
        var query = db.Set<WorkAssignment>();
        return asNoTracking ? query.AsNoTracking() : query;
    }

    // Implement the method
    #region VM Method
    public IQueryable<WorkAssignment> Query(List<int>? companyIds = null)
    {
        var query = BaseQuery(true);

        if (companyIds != null && companyIds.Any())
        {
            query = query.Where(c => companyIds.Contains(c.ClientId));
        }

        return query.Include(c => c.Progress)
            .Include(c => c.Client)
            .Include(c => c.AssignedUsers).ThenInclude(c => c.User);
    }

    public async Task<List<WorkAssignment>> GetWorkList()
    {
        var query = await BuildQueryAsync();
        return [.. query];
    }

    public async Task<List<WorkAssignment>> GetByCompanyIds(List<int> companyIds)
    {
        var query = await BuildQueryAsync();
        if (companyIds.Count == 1)
        {
            var id = companyIds[0];
            return await query.Where(c => c.ClientId == id).ToListAsync();
        }

        return await query.Where(c => companyIds.Contains(c.ClientId)).ToListAsync();
    }

    public async Task<List<WorkAssignment>> GetTodayRemindAssignments()
    {
        var today = DateTime.Today;

        return await db.WorkAssignments
           .Where(c => c.ReminderDate.HasValue && c.ReminderDate.Value.Date == today)
           .Include(c => c.Client)
           .ToListAsync();
    }

    public async Task<List<WorkAssignment>> GetDueSoonAssignments(int day = 7)
    {
        // Get the current date
        var today = DateTime.Today;
        var endDate = today.AddDays(day);

        // Get the assignments that are due within the next 7 days
        return await db.WorkAssignments
           // .Where(c => c.DueDate >= today && c.DueDate < endDate.AddDays(1)) // 小于隔天 00:00
           .Include(c => c.Client)
           .ToListAsync();
    }
    #endregion

    //Rewrite the GetAllAsync method
    protected override Task<IQueryable<WorkAssignment>> BuildQueryAsync()
    {
        // Do you query here
        var query = db.WorkAssignments
                  .Include(c => c.Progress)
                  .Include(c => c.Client)
                  .Include(c => c.AssignedUsers).ThenInclude(c => c.User)
                  .AsNoTracking();

        return Task.FromResult(query);
    }

    //Rewrite the GetWithIncludesAsync method
    protected override Task<IQueryable<WorkAssignment>> BuildQueryWithIncludesAsync()
    {
        //Default query no action
        var query = db.WorkAssignments
                 .Include(c => c.Progress)
                 .Include(c => c.Client)
                 .Include(c => c.AssignedUsers).ThenInclude(c => c.User)
                 .AsNoTracking();

        return Task.FromResult(query);
    }

    //Rewrite the GetSingleAsync method
    protected override Task<IQueryable<WorkAssignment>> BuildGetByIdQueryAsync()
    {
        //Default query no action
        return Task.FromResult(db.Set<WorkAssignment>().AsQueryable());

        // Do you query here
        // var query = db.TableNames;
        // return Task.FromResult(query);    
    }

    //Add the method that want to perform before delete the entity
    protected override async Task BeforeRemove(WorkAssignment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before add the entity
    protected override async Task BeforeAdd(WorkAssignment entity)
    {
        //Do you logic here
    }

    //Add the method that want to perform before update the entity
    protected override async Task BeforeUpdate(WorkAssignment entity)
    {
        //Do you logic here
    }
}
