using SWSA.MvcPortal.Dtos.Requests.Contacts;
using SWSA.MvcPortal.Entities.Contacts;

namespace SWSA.MvcPortal.Services.Interfaces.Clients;

// <auto-generated />
public interface IOfficialContactService
{
    Task<OfficialContact?> GetByIdAsync(int id);
    // Define your method here
    Task<bool> Delete(int ownerId);
    Task<OfficialContact> UpsertContact(UpsertOfficialContactRequest req);
}
