using Microsoft.AspNetCore.Components.Forms;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Dtos.Requests.Contacts;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;

// <auto-generated />
public interface IOfficialContactService
{
    Task<OfficialContact?> GetByIdAsync(int id);
    // Define your method here
    Task<bool> Delete(int ownerId);
    Task<OfficialContact> UpsertContact(UpsertOfficialContactRequest req);
}
