using SWSA.MvcPortal.Dtos.Requests.Companies;

namespace SWSA.MvcPortal.Services.Interfaces.CompanyProfile;
// <auto-generated />
public interface ICompanyComplianceDateService
{
    // Define your method here
    Task<bool> Edit(EditCompanyComplianceDate req);
}
