using Mapster;
using SWSA.MvcPortal.Entities.Contacts;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.Contacts;

// <auto-generated />
public class OfficialContactMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<OfficialContact, OfficialContact>();
    }
}
        