using SWSA.MvcPortal.Models.SystemAuditLogs;

namespace SWSA.MvcPortal.Services.Interfaces.Systems;
// <auto-generated />
public interface ISystemAuditLogService
{
    Task<SystemAuditLogVM> GetLogById(int id);
    Task<List<SystemAuditLogListVM>> GetLogs();

    // Define your method here
    void LogInBackground(SystemAuditLogEntry entry);
}
