using SWSA.MvcPortal.Commons.Services.Messaging.Models;
using SWSA.MvcPortal.Entities.Systems;

namespace SWSA.MvcPortal.Services.Interfaces.Systems;
// <auto-generated />
public interface ISystemNotificationLogService
{
    // Define your method here
    Task AddLog(MessagingResult result);
    Task<List<SystemNotificationLog>> GetLogs();
}
