using Mapster;
using SWSA.MvcPortal.Entities.Systems;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.Scheduler;

// <auto-generated />
public class ScheduledJobMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<ScheduledJob, ScheduledJob>();
    }
}
        