using AutoMapper;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Commons.Attributes;
using SWSA.MvcPortal.Commons.Extensions;
using System.Reflection;
using SWSA.MvcPortal.Commons.Services.BackgroundQueue;
using SWSA.MvcPortal.Persistence;
using Microsoft.EntityFrameworkCore;

namespace SWSA.MvcPortal.Services.SystemInfra;

// <auto-generated />
public class SystemAuditLogService(
IServiceProvider serviceProvider,
IBackgroundTaskQueue queue,
IUserContext userContext,
IMapper mapper,
AppDbContext db
) : ISystemAuditLogService
{
    private readonly DbSet<SystemAuditLog> auditLogs = db.Set<SystemAuditLog>();

    #region VM/DTO Query Method 
    public async Task<List<SystemAuditLogListVM>> GetLogs()
    {
        var data = await auditLogs.ToListAsync();
        return mapper.Map<List<SystemAuditLogListVM>>(data);
    }

    public async Task<SystemAuditLogVM> GetLogById(int id)
    {
        var data = await auditLogs.FirstOrDefaultAsync(c => c.Id == id);
        Guard.AgainstNullData(data, "System Audit Log not found");

        return mapper.Map<SystemAuditLogVM>(data);
    }
    #endregion

    public void LogInBackground(SystemAuditLogEntry entry)
    {
        //Make sure get at main scope 
        var performedBy = userContext.Name;
        var performedById = userContext.EntityId;

        queue.Queue(async token =>
        {
            using var scope = serviceProvider.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            var log = new SystemAuditLog
            {
                Module = entry.Module.ToString(),
                ActionType = entry.ActionType.ToString(),
                EntityId = entry.EntityId,
                Message = entry.Message,
                ChangeSummaryJson = BuildChangeSummary(entry.OldData, entry.NewData),
                PerformedBy = performedBy,
                PerformedByUserId = performedById,
                PerformedAt = DateTime.Now
            };
            db.Add(log);
            await db.SaveChangesAsync(token);
        });
    }

    private string? BuildChangeSummary(object? oldVal, object? newVal)
    {
        if (newVal == null) return null;

        var dict = new Dictionary<string, ChangeSummaryVM>();
        var props = newVal.GetType().GetProperties();

        foreach (var prop in props)
        {
            var auditAttr = prop.GetCustomAttribute<SystemAuditLogAttribute>();
            if (auditAttr == null) continue;

            var displayName = auditAttr.Name;
            var oldValue = oldVal != null ? prop.GetValue(oldVal) : null;
            var newValue = prop.GetValue(newVal);

            var oldStr = ConvertToDisplayString(oldValue);
            var newStr = ConvertToDisplayString(newValue);

            if (oldStr != newStr || oldStr == null)
                dict[displayName] = new ChangeSummaryVM(displayName, oldStr, newStr);

        }

        return dict.Count > 0 ? JsonConvert.SerializeObject(dict.Values) : null;
    }


    private string? ConvertToDisplayString(object? value)
    {
        if (value == null) return null;

        if (value is Enum e)
            return e.GetDisplayName();

        return value.ToString();
    }
}