using SWSA.MvcPortal.Repositories.Interfaces;
using AutoMapper;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Commons.Services.BackgroundQueue;
using Newtonsoft.Json;
using SWSA.MvcPortal.Commons.Attributes;
using SWSA.MvcPortal.Commons.Extensions;
using SWSA.MvcPortal.Commons.Services.SystemAuditLog;
using System.Reflection;

namespace SWSA.MvcPortal.Services.SystemInfra;

// <auto-generated />
public class SystemAuditLogService(
IServiceProvider serviceProvider,
ISystemAuditLogRepository repo,
IBackgroundTaskQueue queue,
IUserContext userContext,
IMapper mapper
) : ISystemAuditLogService
{
    #region VM/DTO Query Method 
    #endregion
    public async Task<List<SystemAuditLogListVM>> GetLogs()
    {
        var data = await repo.GetAllAsync();
        return mapper.Map<List<SystemAuditLogListVM>>(data);
    }

    public async Task<SystemAuditLogVM> GetLogById(int id)
    {
        var data = await repo.GetByIdAsync(id);
        Guard.AgainstNullData(data, "System Audit Log not found");

        return mapper.Map<SystemAuditLogVM>(data);
    }

    public void LogInBackground(SystemAuditLogEntry entry)
    {
        queue.Queue(async token =>
        {
            using var scope = serviceProvider.CreateScope();
            var repo = scope.ServiceProvider.GetRequiredService<ISystemAuditLogRepository>();
            var url = AuditNavigationService.GenerateUrl(entry.Module, entry.EntityId);
            var log = new SystemAuditLog
            {
                Module = entry.Module.ToString(),
                ActionType = entry.ActionType.ToString(),
                EntityId = entry.EntityId,
                EntityName = entry.EntityName,
                NavigateUrl = url,
                ChangeSummaryJson = BuildChangeSummary(entry.OldData, entry.NewData),
                PerformedBy = userContext.Name,
                PerformedByUserId = userContext.EntityId,
                PerformedAt = DateTime.Now
            };
            repo.Add(log);
            await repo.SaveChangesAsync();
        });
    }

    private string? BuildChangeSummary(object? oldVal, object? newVal)
    {
        if (newVal == null) return null;

        var dict = new Dictionary<string, ChangeSummaryVM>();
        var props = newVal.GetType().GetProperties();

        foreach (var prop in props)
        {
            var auditAttr = prop.GetCustomAttribute<SystemAuditLogAttribute>();
            if (auditAttr == null) continue;

            var displayName = auditAttr.Name;
            var oldValue = oldVal != null ? prop.GetValue(oldVal) : null;
            var newValue = prop.GetValue(newVal);

            var oldStr = ConvertToDisplayString(oldValue);
            var newStr = ConvertToDisplayString(newValue);

            if (oldStr != newStr || oldStr == null)
                dict[displayName] = new ChangeSummaryVM(displayName, oldStr, newStr);

        }

        return dict.Count > 0 ? JsonConvert.SerializeObject(dict.Values) : null;
    }


    private string? ConvertToDisplayString(object? value)
    {
        if (value == null) return null;

        if (value is Enum e)
            return e.GetDisplayName();

        return value.ToString();
    }
}