using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Commons.Services.Messaging;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.SystemInfra;

// <auto-generated />
public class SystemNotificationLogService(
ISystemNotificationLogRepository repo
    ) : ISystemNotificationLogService
{
    #region VM/DTO Query Method 
    public async Task<List<SystemNotificationLog>> GetLogs()
    {
        var data = await repo.GetAllAsync();
        return [.. data];
    }
    #endregion

    public async Task AddLog(MessagingResult result)
    {
        var log = new SystemNotificationLog
        {
            Channel = result.MessageEnvelope.Channel,
            Recipient = result.MessageEnvelope.Recipient,
            TemplateCode = result.MessageEnvelope.TemplateCode,
            IsSuccess = result.IsSuccess,
            ResultMessage = result.Message,
            Reason = result.MessageEnvelope.Reason,
        };

        repo.Add(log);
        await repo.SaveChangesAsync();
    }
}