using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.WorkAssignment;

// <auto-generated />
public class CompanyWorkProgressMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyWorkProgress, CompanyWorkProgress>();
    }
}
        