using Mapster;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.WorkAssignment;

// <auto-generated />
public class CompanyWorkAssignmentMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyWorkAssignment, CompanyWorkAssignment>();
    }
}
        