using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.DocumentRecords;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.WorkAssignment;

// <auto-generated />
public class DocumentRecordMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<DocumentRecord, DocumentRecord>();
        config.ForType<DocumentRecord, DocumentRecordVM>()
      .Map(dest => dest.DocumentId, src => src.Id)
      .Map(dest => dest.WorkAssignmentId, src => src.WorkAssignment.Id)
      .Map(dest => dest.WorkType, src => src.WorkAssignment.WorkType)
      .Map(dest => dest.FlowType, src => src.DocumentFlow)
      .Map(dest => dest.AttachmentPath, src => src.AttachmentFilePath)
      .Map(dest => dest.CompanyId, src => src.WorkAssignment.Company.Id)
      .Map(dest => dest.CompanyName, src => src.WorkAssignment.Company.Name)
      .Map(dest => dest.StaffName, src => src.HandledByStaff.FullName ?? "N/A")
      .Map(dest => dest.HandledByStaffId, src => src.HandledByStaff.StaffId ?? src.HandledByStaffId.ToString());
    }
}
        