using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.WorkAssignment;

// <auto-generated />
public class WorkAssignmentMonthMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<WorkAssignmentMonth, WorkAssignmentMonth>();
        config.ForType<WorkAssignmentMonth, CompanyWorkMonthVM>();
    }
}
        