// <auto-generated />

using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;

public interface IMsicCodeService 
{
    // Define your method here
    Task<List<MsicCode>> GetMsicCodeAsync();
}
