using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.DocumentRecords;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.DocumentRecords;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using AutoMapper;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Services.Interfaces.WorkAssignments;
using SWSA.MvcPortal.Persistence;
using Microsoft.EntityFrameworkCore;

namespace SWSA.MvcPortal.Services.WorkAssignments;

// <auto-generated />
public class DocumentRecordService(
IMapper mapper,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
AppDbContext db
) : IDocumentRecordService
{
    private readonly DbSet<DocumentRecord> documentRecords = db.Set<DocumentRecord>();

    #region VM/DTO Query Method 
    public async Task<List<DocumentRecord>> GetDocumentRecordsByDepartment(string department)
    {
        var data = await documentRecords.Where(c => c.Department == department).ToListAsync();
        return data;
    }

    public async Task<List<DocumentRecordVM>> GetDocumentRecords()
    {
        var data = await documentRecords.ToListAsync();
        return mapper.Map<List<DocumentRecordVM>>(data);
    }

    public async Task<DocumentRecordVM> GetDocumentRecordById(int id)
    {
        var data = await documentRecords.FirstOrDefaultAsync(c => c.Id == id);
        Guard.AgainstNullData(data, "DocumentRecord not found");
        return mapper.Map<DocumentRecordVM>(data!);
    }
    #endregion

    public async Task<DocumentRecord> CreateDocument(DocumentRecordRequest doc)
    {
        var data = mapper.Map<DocumentRecord>(doc);
        data.HandledByStaffId = userContext.EntityId;
        db.Add(data);

        await db.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.DocumentRecord, data.Id.ToString(), $"Document: {data.Id}", data);
        sysAuditService.LogInBackground(log);
        return data;
    }

    public async Task<bool> CreateDocuments(DocumentRecordListRequest req, List<IFormFile> files)
    {
        List<DocumentRecord> records = [];
        for (int i = 0; i < req.Documents.Count; i++)
        {
            var doc = req.Documents[i];
            var data = mapper.Map<DocumentRecord>(doc);
            data.HandledByStaffId = userContext.EntityId;
            db.Add(data);
        }

        await db.SaveChangesAsync();
        foreach (var doc in records)
        {
            var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOwner, doc.Id.ToString(), $"Document: {doc.Id}", doc);
            sysAuditService.LogInBackground(log);
        }
        return true;
    }

    public async Task<bool> Delete(int docId)
    {
        var doc = await documentRecords.FirstOrDefaultAsync(c => c.Id == docId);
        Guard.AgainstNullData(doc, "Document not found");
        db.Remove(doc!);
        await db.SaveChangesAsync();


        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOwner, doc!.Id.ToString(), $"Document: {doc.Id}", doc);
        sysAuditService.LogInBackground(log);
        return true;
    }
}