using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class CompanyWorkAssignmentMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyWorkAssignment, CompanyWorkAssignment>();
        config.ForType<CompanyWorkAssignment, CompanyWorkVM>()
          .Map(dest => dest.TaskId, src => src.Id)
          .Map(dest => dest.ActivitySize, src => src.CompanyActivityLevel)
          .Map(dest => dest.PlannedMonths, src => src.PlannedMonths.Select(c => c.Month));
    }
}
