using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class CompanyComplianceDateMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyComplianceDate, CompanyComplianceDate>();
    }
}
        