using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class CompanyCommunicationContactMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyCommunicationContact, CompanyCommunicationContact>();
    }
}
        