using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class CompanyStrikeOffSubmissionMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyStrikeOffSubmission, CompanyStrikeOffSubmission>();
    }
}
        