using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class CompanyWorkProgressMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyWorkProgress, CompanyWorkProgress>();
        config.ForType<CompanyWorkProgress, CompanyWorkProgressVM>()
         .Map(dest => dest.ProgressId, src => src.Id);
    }
}
        