using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class DocumentRecordMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<DocumentRecord, DocumentRecord>();
    }
}
        