using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class WorkAssignmentAuditMonthMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<WorkAssignmentAuditMonth, WorkAssignmentAuditMonth>();
        config.ForType<WorkAssignmentAuditMonth, CompanyWorkMonthVM>();

    }
}
        