using Mapster;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Commons.MapsterConfigs;

// <auto-generated />
public class WorkAssignmentUserMappingMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<WorkAssignmentUserMapping, WorkAssignmentUserMapping>();
        config.ForType<WorkAssignmentUserMapping, CompanyWorkUserVM>()
     .Map(dest => dest.StaffId, src => src.User.StaffId)
     .Map(dest => dest.StaffName, src => src.User.FullName)
     .Map(dest => dest.Role, src => src.User.Role)
     .Map(dest => dest.IsAssignedToAccount, src => src.Department == DepartmentType.Account)
     .Map(dest => dest.IsAssignedToAudit, src => src.Department == DepartmentType.Audit);

    }
}
        