using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Services.Interfaces.WorkAssignments;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    Task<int> Create(CreateCompanyWorkAssignmentRequest req);
    Task<int> RequestWorkAssignment(WorkAssignmentRequest req);

    Task<Entities.WorkAssignment> Delete(int taskId);
    Task<bool> Edit(EditCompanyWorkAssignmentRequest req);
    Task<Entities.WorkAssignment> GetWorkAssignmentById(int taskId);
    Task<T> GetWorkAssignmentById<T>(int taskId) where T : Entities.WorkAssignment;

    // Define your method here
    Task<List<Entities.WorkAssignment>> GetWorkAssignments();
    Task<List<T>> GetWorkAssignments<T>() where T : Entities.WorkAssignment;
    Task<List<CompanyWorkCalendarVM>> GetWorkCalendarEvents();
    Task<bool> UpdateWork<TRequest, TEntity>(TRequest req)
        where TRequest : IWorkAssignmentUpdater<TEntity>
        where TEntity : Entities.WorkAssignment;
}
