using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Services.Interfaces.WorkAssignments;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    Task<int> Create(CreateCompanyWorkAssignmentRequest req);
    Task<int> RequestWorkAssignment(WorkAssignmentRequest req);

    Task<WorkAssignment> Delete(int taskId);

    Task<T> GetWorkAssignmentById<T>(int taskId) where T : WorkAssignment;

    // Define your method here
    Task<List<T>> GetWorkAssignments<T>() where T : WorkAssignment;
    Task<bool> UpdateWork<TRequest, TEntity>(TRequest req)
        where TRequest : IWorkAssignmentUpdater<TEntity>
        where TEntity : Entities.WorkAssignment;
}
