using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;

namespace SWSA.MvcPortal.Services.Interfaces.WorkAssignments;
// <auto-generated />
public interface IWorkAssignmentUserMappingService
{
    // Define your method here
    Task<int> AddUser(WorkUserRequest req);
    Task<bool> RemoveUser(WorkUserRequest req);
}
