using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IAnnualReturnSubmissionRepository : IRepositoryBase<AnnualReturnSubmission>
{
    Task<List<AnnualReturnSubmissionVM>> GetListVMAsync();

    // Define your method here
    Task<AnnualReturnSubmissionVM> GetVMByIdAsync(int id);
}
