using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyRepository : IRepositoryBase<Company>
{
    Task<List<Company>> GetCompaniesByIdsAsync(List<int> companyIds);

    // Define your method here
    Task<List<Company>> GetCompaniesByUserId(int userId);
}
