
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyWorkAssignmentRepository : IRepositoryBase<CompanyWorkAssignment>
{
    Task<List<CompanyWorkAssignment>> GetByCompanyIds(List<int> companyIds);

    // Define your method here
    /// <summary>
    /// Get the assignments that are due within the {day} days
    /// </summary>
    /// <param name="day"> Default is 7 days</param>
    /// <returns></returns>
    Task<List<CompanyWorkAssignment>> GetDueSoonAssignments(int day = 7);
    Task<CompanyWorkAssignment> GetUpdateVMById(int id);
}
