
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyCommunicationContactRepository : IRepositoryBase<CompanyCommunicationContact>
{
    Task<List<CompanyCommunicationContact>> GetAllByCompanyIdAsync(int companyId);

    // Define your method here
}
