
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyStaffRepository : IRepositoryBase<CompanyStaff>
{
    Task<bool> ExistUsernameInCompanyExcludingStaffId(int companyId, string username,string excludedStaffId);
    Task<List<CompanyStaff>> GetAllByCompanyIdAsync(int companyId);

    // Define your method here
    Task<CompanyStaff> GetByStaffId(string staffId);

}
