using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompanyStrikeOffSubmission;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyStrikeOffSubmissionRepository : IRepositoryBase<CompanyStrikeOffSubmission>
{
    Task<CompanyStrikeOffSubmission> GetByCompanyId(int companyId);

    // Define your method here
    Task<List<CompanyStrikeOffSubmissionVM>> GetListVMAsync();
    Task<CompanyStrikeOffSubmissionVM> GetVMByIdAsync(int id);
}
