
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Companies;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyRepository : IRepositoryBase<Company>
{
    Task<List<Company>> GetCompanies();
    Task<List<Company>> GetCompaniesByIdsAsync(List<int> companyIds);
    Task<List<Company>> GetCompaniesByType(ClientType type);
    Task<List<CompanySelectionVM>> GetSelectionsVMAsync();
    Task<CompanySimpleInfoVM> GetSimpleInfoVMByIdAsync(int id);
    Task<List<CompanySelectionVM>> GetSelectionsVMByTypeAsync(ClientType type);
}
