
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICommunicationContactRepository : IRepositoryBase<CommunicationContact>
{
    Task<List<CommunicationContact>> GetAllByCompanyIdAsync(int companyId);

    // Define your method here
}
