// <auto-generated />
using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

public interface ICompanyTypeRepository : IRepositoryBase<CompanyType>
{
    // Define your method here
}
