using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface ICompanyStrikeOffSubmissionRepository : IRepositoryBase<CompanyStrikeOffSubmission>
{
    // Define your method here
}
