
using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IDocumentRecordRepository : IRepositoryBase<DocumentRecord>
{
    Task<List<DocumentRecord>> GetDocumentRecordsByCompanyDepartmentId(int companyDepartmentId);

    // Define your method here
    Task<List<DocumentRecord>> GetDocumentRecordsByCompanyId(int companyId);
    Task<List<DocumentRecord>> GetDocumentRecordsByStaffId(string staffId);
}
