using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IDocumentRecordRepository : IRepositoryBase<DocumentRecord>
{
    Task<List<DocumentRecord>> GetDocumentRecordsByCompanyDepartmentId(int companyDepartmentId);

    // Define your method here
    Task<List<DocumentRecord>> GetDocumentRecordsByCompanyId(int companyId);
    Task<List<DocumentRecord>> GetDocumentRecordsByCompanyIds(List<int> companyIds);
    Task<List<DocumentRecord>> GetDocumentRecordsByStaffId(string staffId);
}
