
using System;
using System.Threading.Tasks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IScheduledJobRepository : IRepositoryBase<ScheduledJob>
{
    // Define your method here
    Task<List<ScheduledJob>> GetDefaultAndEnabledJobs();
    Task<ScheduledJob> GetScheduledByJobKeyAsync(string jobkey);
}
