
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IWorkAssignmentUserMappingRepository : IRepositoryBase<WorkAssignmentUserMapping>
{
    // Define your method here
    Task<WorkAssignmentUserMapping?> GetByUserIdAsync(int taskId, int userId);
    Task<List<WorkAssignmentUserMapping>> GetTodayRemindUserAssignmentsAsync();
}
