using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IWorkAssignmentMonthRepository : IRepositoryBase<WorkAssignmentMonth>
{
    // Define custom methods if needed
}