using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IWorkAssignmentAuditMonthRepository : IRepositoryBase<WorkAssignmentAuditMonth>
{
    // Define custom methods if needed
}