using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Repositories.Interfaces;

// <auto-generated />
public interface IWorkAssignmentRepository : IRepositoryBase<WorkAssignment>
{
    Task<List<WorkAssignment>> GetByCompanyIds(List<int> companyIds);
    Task<List<WorkAssignment>> GetWorkList();
    // Define your method here
    /// <summary>
    /// Get the assignments that are due within the {day} days
    /// </summary>
    /// <param name="day"> Default is 7 days</param>
    /// <returns></returns>
    Task<List<WorkAssignment>> GetDueSoonAssignments(int day = 7);
    Task<List<WorkAssignment>> GetTodayRemindAssignments();
    IQueryable<WorkAssignment> Query(List<int>? companyIds = null);
}
