using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.WorkAssignment;

// <auto-generated />
public class CompanyWorkProgressService(
ICompanyWorkProgressRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyWorkProgressService
{
    #region VM/DTO Query Method 
    #endregion

    public async Task<bool> Edit(EditCompanyWorkProgressRequest req)
    {
        var progress = await repo.GetByIdAsync(req.ProgressId);
        Guard.AgainstNullData(progress, "Work Progress not found.");

        var oldData = progress.DeepClone();

        progress!.StartDate = req.StartDate;
        progress.EndDate = req.EndDate;
        progress.TimeTakenInDays = req.TimeTakenInDays;
        progress.Status = req.Status;
        progress.ProgressNote = req.ProgressNote;
        progress.UpdatedAt = DateTime.Now;

        repo.Update(progress);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyWorkAssignment, progress.WorkAssignmentId.ToString(), $"Work Assignment Progress", oldData, progress);
        sysAuditService.LogInBackground(log);
        return true;
    }

}