using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Microsoft.Extensions.Caching.Memory;
using AutoMapper;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.WorkAssignment;

// <auto-generated />
public class WorkAssignmentUserMappingService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
IWorkAssignmentUserMappingRepository repo,
IUserRepository userRepo
    ) : IWorkAssignmentUserMappingService
{
    #region VM/DTO Query Method 
    #endregion


    public async Task<int> AddUser(WorkUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");

        var mapUser = await repo.GetByUserIdAsync(req.TaskId, user.Id);
        if (mapUser != null)
            throw new BadHttpRequestException($"User already exists in work assignment");

        var entity = new WorkAssignmentUserMapping()
        {
            UserId = user.Id,
            WorkAssignmentId = req.TaskId,
        };

        repo.Add(entity);
        await repo.SaveChangesAsync();
        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyWorkAssignment,
            user.StaffId.ToString(), $"Assign work to User: {user.FullName}", mapUser!);
        sysAuditService.LogInBackground(log);

        return entity.Id;
    }

    public async Task<bool> RemoveUser(WorkUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");

        var mapUser = await repo.GetByUserIdAsync(req.TaskId, user.Id);
        Guard.AgainstNullData(mapUser, "User not found in work assignment");

        repo.Remove(mapUser!);
        await repo.SaveChangesAsync();
        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyWorkAssignment,
            user.StaffId.ToString(), $"Remove User: {user.FullName} from work", mapUser!);
        sysAuditService.LogInBackground(log);

        return true;
    }
}