using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Services.CompanyProfile;

// <auto-generated />
public class CompanyMsicCodeService(
    ICompanyMsicCodeRepository repo
) : ICompanyMsicCodeService
{
    #region VM/DTO Query Method 
    #endregion
}