using SWSA.MvcPortal.Repositories.Interfaces;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Services.Permission;
using AutoMapper;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Dtos.Requests.Users;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Companies;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.CompanyProfile;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using NuGet.Packaging;

namespace SWSA.MvcPortal.Services.CompanyProfile;

// <auto-generated />
public class CompanyService(
    IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyRepository repo,
ICompanyMsicCodeRepository companyMsicCodeRepository,
IMsicCodeRepository msicCodeRepository,
IUserCompanyDepartmentRepository userCompanyDepartmentRepository,
IUserRepository userRepository,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
IPermissionRefreshTracker permissionRefreshTracker
) : ICompanyService
{

    #region VM/DTO Query Method 
    public async Task<List<CompanyListVM>> GetCompanyListVMAsync()
    {
        var data = userContext.IsSuperAdmin ? await repo.GetListVMAsync()
                : await repo.GetListVMByUserIdAsync(userContext.EntityId);
        return data;
    }

    public async Task<List<CompanyListVM>> GetCompanyListByTypeAsync(CompanyType type)
    {
        var data = userContext.IsSuperAdmin ? await repo.GetListVMByTypeAsync(type)
            : await repo.GetListVMByUserIdAndTypeAsync(userContext.EntityId, type);
        return data;
    }

    public async Task<List<CompanySelectionVM>> GetCompanySelectionByTypeAsync(CompanyType type)
    {
        var data = userContext.IsSuperAdmin ? await repo.GetSelectionsVMByTypeAsync(type)
            : await repo.GetSelectionsVMByUserIdAndTypeAsync(userContext.EntityId, type);
        return data;
    }

    public async Task<List<CompanySelectionVM>> GetCompanySelectionAsync()
    {
        var data = userContext.IsSuperAdmin ? await repo.GetSelectionsVMAsync()
            : await repo.GetSelectionsVMByUserIdAsync(userContext.EntityId);
        return data;
    }

    public async Task<CompanySecretaryVM> GetCompanyForSecretaryVMByIdAsync(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);
        var data = await repo.GetSecretaryVMByIdAsync(companyId);
        Guard.AgainstNullData(data, "Company not found");

        return data;
    }

    public async Task<List<SecretaryCompanyListVM>> GetSecretaryCompanyListVMByYearAsync(int year)
    {
        var data = await repo.GetSecretaryCompanyListVMByYearAsync(year);
        return data;
    }

    public async Task<CompanySimpleInfoVM> GetCompanySimpleInfoVMByIdAsync(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);

        var data = await repo.GetSimpleInfoVMByIdAsync(companyId);
        return data;
    }
    #endregion

    public async Task<Company> GetCompanyByIdAsync(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);
        var data = await repo.GetWithIncludedByIdAsync(companyId);
        Guard.AgainstNullData(data, "Company not found");

        return data!;
    }

    public async Task<int> Create(CreateCompanyRequest req)
    {
        if (req.HandleUsers.Count == 0)
            throw new BusinessLogicException("Please select at least one user to handle this company");

        Company cp = mapper.Map<Company>(req);

        await repo.BeginTransactionAsync();
        try
        {
            repo.Add(cp);
            await repo.SaveChangesAsync();

            //Process handle user associated
            var staffIds = req.HandleUsers.Select(x => x.StaffId).ToHashSet();
            var userIds = await userRepository.GetDictionaryIdByStaffIdsAsync([.. staffIds]);
            var allUserCompanyDepartments = new List<UserCompanyDepartment>();
            foreach (var handleUser in req.HandleUsers)
            {
                var userId = userIds[handleUser.StaffId];
                var noRepeatDepartments = handleUser.Departments.Select(x => x).Distinct().ToList();

                var entities = UserCompanyDepartmentMapper.ToEntities(noRepeatDepartments, cp.Id, userId);
                allUserCompanyDepartments.AddRange(entities);

                permissionRefreshTracker.MarkRefreshNeeded(handleUser.StaffId);
            }

            userCompanyDepartmentRepository.AddRange(allUserCompanyDepartments);
            await userCompanyDepartmentRepository.SaveChangesAsync();

            await repo.CommitTransactionAsync();
        }
        catch
        {
            await repo.RollbackTransactionAsync();
            throw;
        }

        ClearCompaniesCache();
        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.Company, cp.Id.ToString(), cp.Name, cp);
        sysAuditService.LogInBackground(log);
        return cp.Id;
    }

    public async Task<bool> Edit(EditCompanyRequest req)
    {
        Guard.AgainstUnauthorizedCompanyAccess(req.CompanyId, null, userContext);

        var data = await repo.GetWithIncludedByIdAsync(req.CompanyId);
        Guard.AgainstNullData(data, "Company not found");
        var oldData = data.DeepClone();

        data!.Name = req.CompanyName;
        data.RegistrationNumber = req.RegistrationNumber;
        data.EmployerNumber = req.EmployerNumber;
        data.TaxIdentificationNumber = req.TaxIdentificationNumber;
        data.YearEndMonth = req.YearEndMonth;
        data.IncorporationDate = req.IncorporationDate;
        data.CompanyType = req.CompanyType;
        data.CompanyStatus = req.CompanyStatus;
        data.CompanyActivityLevel = req.CompanyActivityLevel;

        await SyncMsicCodes(data, req.MsicCodeIds?.ToHashSet() ?? new());

        repo.Update(data);
        await repo.SaveChangesAsync();
        ClearCompaniesCache(data.Id);

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.Company, data.Id.ToString(), data.Name, oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<Company> Delete(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);

        var data = await repo.GetByIdAsync(companyId);
        Guard.AgainstNullData(data, "Company not found");

        ////Remove in db
        //await repo.BeginTransactionAsync();
        //repo.Remove(data!);
        //await repo.SaveChangesAsync();

        //await repo.CommitTransactionAsync();

        //soft delete
        data!.IsDeleted = true;
        repo.Update(data);
        await repo.SaveChangesAsync();

        ClearCompaniesCache();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.Company, data.Id.ToString(), data.Name, data);
        sysAuditService.LogInBackground(log);
        return data!;
    }

    private async Task<List<Company>> GetCompaniesFromCacheAsync()
    {
        if (cache.TryGetValue(DataCacheKey.Companies, out List<Company>? companies))
        {
            return companies ?? [];
        }

        // Fetch data from the database or any other source
        companies = [.. await repo.GetAllAsync()];
        if (companies.Count > 0)
        {
            cache.Set(DataCacheKey.Companies, companies, cacheOptions);
        }
        return companies;
    }

    private async Task<Company?> GetCompanyByIdFromCacheAsync(int id)
    {
        string cacheKey = $"{DataCacheKey.Companies}_{id}";
        string cacheDetailKey = $"{cacheKey}_Details";
        if (cache.TryGetValue(cacheDetailKey, out Company? cpDetails))
        {
            return cpDetails;
        }

        if (cache.TryGetValue(cacheKey, out Company? cp))
        {
            return cp;
        }
        // Fetch data from the database or any other source
        cp = await repo.GetByIdAsync(id);
        if (cp != null)
        {
            cache.Set(cacheKey, cp, cacheOptions);
        }
        return cp;
    }

    private async Task<Company?> GetCompanyWithIncludedByIdFromCacheAsync(int id)
    {
        string cacheKey = $"{DataCacheKey.Companies}_{id}";
        string cacheDetailKey = $"{cacheKey}_Details";

        if (cache.TryGetValue(cacheDetailKey, out Company? cp))
        {
            return cp;
        }
        // Fetch data from the database or any other source
        cp = await repo.GetWithIncludedByIdAsync(id);
        if (cp != null)
        {
            cache.Set(cacheDetailKey, cp, cacheOptions);
            //remove old and no detail cache
            cache.Remove(cacheKey);
        }
        return cp;
    }

    private void ClearCompaniesCache(int? id = 0)
    {
        string cacheKey = $"{DataCacheKey.Companies}";
        cache.Remove(cacheKey);
        if (id.HasValue && id > 0)
        {
            cache.Remove($"{cacheKey}_{id}");
            cache.Remove($"{cacheKey}_{id}_Details");
        }
    }

    private async Task SyncMsicCodes(Company data, HashSet<int> requestedMsicIds)
    {
        var existingMsicIds = data.MsicCodes.Select(x => x.MsicCodeId).ToHashSet();
        var msicIdsToAdd = requestedMsicIds.Except(existingMsicIds).ToList();
        var msicsToRemove = data.MsicCodes
          .Where(x => !requestedMsicIds.Contains(x.MsicCodeId)).ToList();
        var msicIdsToRemove = msicsToRemove.Select(x => x.MsicCodeId).ToList();


        if (msicIdsToAdd.Count > 0)
        {
            var msicEntities = await msicCodeRepository.GetByIdsAsync(msicIdsToAdd);
            data.MsicCodes.AddRange(msicEntities.Select(msic => new CompanyMsicCode(msic.Id)));
        }

        foreach (var msic in msicsToRemove)
        {
            //Remove in data entity
            data.MsicCodes.Remove(msic);
        }

        //Remove in db
        var msicRemoveEntities = await companyMsicCodeRepository.GetByIdsAsync(msicIdsToRemove);
        companyMsicCodeRepository.RemoveRange(msicRemoveEntities);
    }
}