using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Entities;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.CompanyProfile;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.CompanyProfile;

// <auto-generated />
public class CompanyComplianceDateService(
ICompanyComplianceDateRepository repo,
IUserContext userContext,
ISystemAuditLogService sysAuditService
    ) : ICompanyComplianceDateService
{
    #region VM/DTO Query Method 
    #endregion

    public async Task<bool> Edit(EditCompanyComplianceDate req)
    {
        Guard.AgainstUnauthorizedCompanyAccess(req.CompanyId, null, userContext);
        var data = await repo.GetByCompanyId(req.CompanyId);
        bool isNew = data == null;

        data ??= new CompanyComplianceDate();

        var oldData = data.DeepClone();

        if (isNew)
        {
            data.CompanyId = req.CompanyId;
            repo.Add(data);
        }
        else
        {
            data.AccountDueDate = req.AccountDueDate;
            data.AnniversaryDate = req.AnniversaryDate;
            data.AGMDate = req.AGMDate;
            data.AnnualReturnDueDate = req.AnnualReturnDueDate;
            data.FirstYearAccountStart = req.FirstYearAccountStart;
            data.Notes = req.Notes;
        }

        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyComplianceDate, data.CompanyId.ToString(), "Company Compliance Date", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }
}