using SWSA.MvcPortal.Repositories.Interfaces;
using AutoMapper;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.CompanyProfile;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.CompanyProfile;

// <auto-generated />
public class CompanyOwnerService(
IMapper mapper,
ICompanyOwnerRepository repo,
ISystemAuditLogService sysAuditService,
IUserContext userContext
) : ICompanyOwnerService
{
    #region VM/DTO Query Method 
    #endregion

    public async Task<int> Create(CreateCompanyOwnerRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }

        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = mapper.Map<CompanyOwner>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyOwner, data.CompanyId.ToString(), $"Company Owner: {data.NamePerIC}", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> Edit(EditCompanyOwnerRequest req)
    {
        Guard.AgainstUnauthorizedCompanyAccess(req.CompanyId, null, userContext);

        var data = await repo.GetByIdAsync(req.OwnerId);

        Guard.AgainstNullData(data, "Company Owner not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.NamePerIC = req.NamePerIC;
        data.ICOrPassportNumber = req.ICOrPassportNumber;
        data.Position = req.Position;
        data.TaxReferenceNumber = req.TaxReferenceNumber;
        data.Email = req.Email;
        data.PhoneNumber = req.PhoneNumber;
        data.OwnershipType = req.OwnershipType;

        repo.Update(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyOwner, data.CompanyId.ToString(), $"Company Owner: {data.NamePerIC}", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> Delete(int ownerId)
    {
        var data = await repo.GetByIdAsync(ownerId);
        Guard.AgainstNullData(data, "Company Owner not found");
        Guard.AgainstUnauthorizedCompanyAccess(data!.CompanyId, null, userContext);

        repo.Remove(data!);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOwner, data!.CompanyId.ToString(), $"Company Owner: {data.NamePerIC}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

}