using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;
using AutoMapper;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.CompanyProfile;

// <auto-generated />
public class CompanyOfficialContactService(
IMapper mapper,
IUserContext userContext,
ICompanyOfficialContactRepository repo,
ISystemAuditLogService sysAuditService
) : ICompanyOfficialContactService
{
    #region VM/DTO Query Method 
    #endregion
    public async Task<int> Create(CreateCompanyOfficialContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }

        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = mapper.Map<CompanyOfficialContact>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> Edit(EditCompanyOfficialContactRequest req)
    {
        if (req.CompanyId.HasValue)
        {
            Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);
        }

        var data = await repo.GetByIdAsync(req.ContactId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.Address = req.Address;
        data.OfficeTel = req.OfficeTel;
        data.Email = req.Email;
        data.Remark = req.Remark;

        repo.Update(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> Delete(int ownerId)
    {
        var data = await repo.GetByIdAsync(ownerId);
        Guard.AgainstNullData(data, "Company Official Contact not found");

        repo.Remove(data!);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", data);
        sysAuditService.LogInBackground(log);
        return true;
    }
}