// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWSA.MvcPortal.Persistence;

#nullable disable

namespace SWSA.MvcPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523071341_update-company-strike-off")]
    partial class updatecompanystrikeoff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWSA.MvcPortal.Entities.AnnualReturnSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnniversaryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfAnnualReturn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturnedByClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSentToClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetedARDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkAssignmentId")
                        .IsUnique();

                    b.ToTable("AnnualReturnSubmissions");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("EmployerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStrikedOff")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StrikeOffEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StrikeOffStatus")
                        .HasColumnType("int");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearEndMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyCommunicationContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyCommunicationContact");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyComplianceDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AGMDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnniversaryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnnualReturnDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstYearAccountStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyComplianceDates");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyMsicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("MsicCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MsicCodeId");

                    b.ToTable("CompanyMsicCodes");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOfficialContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyOfficialContacts");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICOrPassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePerIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("TaxReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyOwners");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyStrikeOffSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IRBSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SSMStrikeOffDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SSMSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyStrikeOffSubmissions");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyWorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AGMDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ARDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsYearEndTask")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SSMExtensionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceScope")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyWorkAssignments");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyWorkProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBacklog")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJobCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProgressNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeTakenInDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkAssignmentId")
                        .IsUnique();

                    b.ToTable("CompanyWorkProgresses");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BagOrBoxCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentFlow")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("HandledByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HandledByStaffId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.MsicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryReferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MsicCodes");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ScheduledJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastExecuteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TriggerTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobKey");

                    b.HasIndex("UserId");

                    b.HasIndex("JobGroup", "JobKey")
                        .IsUnique();

                    b.ToTable("ScheduledJobs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavigateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemNotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Channel");

                    b.HasIndex("CreatedAt", "TemplateCode");

                    b.ToTable("SystemNotificationLogs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("'StaffId-' + RIGHT('000000' + CAST([Id] AS VARCHAR), 6)", true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.UserCompanyDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompanyDepartment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentAccountMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyWorkAssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyWorkAssignmentId");

                    b.ToTable("WorkAssignmentAccountMonths");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentAuditMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyWorkAssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyWorkAssignmentId");

                    b.ToTable("WorkAssignmentAuditMonths");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentUserMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkAssignmentId", "UserId", "Department")
                        .IsUnique();

                    b.ToTable("WorkAssignmentUserMappings");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.AnnualReturnSubmission", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.CompanyWorkAssignment", "WorkAssignment")
                        .WithOne("Submission")
                        .HasForeignKey("SWSA.MvcPortal.Entities.AnnualReturnSubmission", "WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyCommunicationContact", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("CommunicationContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyComplianceDate", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithOne("ComplianceDate")
                        .HasForeignKey("SWSA.MvcPortal.Entities.CompanyComplianceDate", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyMsicCode", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("MsicCodes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.MsicCode", "MsicCode")
                        .WithMany("CompanyLinks")
                        .HasForeignKey("MsicCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("MsicCode");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOfficialContact", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("OfficialContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOwner", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("Owners")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyStrikeOffSubmission", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithOne("StrikeOffSubmission")
                        .HasForeignKey("SWSA.MvcPortal.Entities.CompanyStrikeOffSubmission", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyWorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyWorkProgress", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.CompanyWorkAssignment", "WorkAssignment")
                        .WithOne("Progress")
                        .HasForeignKey("SWSA.MvcPortal.Entities.CompanyWorkProgress", "WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.DocumentRecord", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "HandledByStaff")
                        .WithMany()
                        .HasForeignKey("HandledByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByStaff");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ScheduledJob", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "User")
                        .WithMany("ScheduledJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", null)
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("CompanyId");

                    b.HasOne("SWSA.MvcPortal.Entities.User", "PerformedByUser")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.UserCompanyDepartment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Company", "Company")
                        .WithMany("UserCompanyDepartments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.User", "User")
                        .WithMany("CompanyDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentAccountMonth", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.CompanyWorkAssignment", "CompanyWorkAssignment")
                        .WithMany("AccountPlannedMonths")
                        .HasForeignKey("CompanyWorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyWorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentAuditMonth", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.CompanyWorkAssignment", "CompanyWorkAssignment")
                        .WithMany("AuditPlannedMonths")
                        .HasForeignKey("CompanyWorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyWorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentUserMapping", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "User")
                        .WithMany("AssignedDepartmentTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.CompanyWorkAssignment", "WorkAssignment")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Company", b =>
                {
                    b.Navigation("CommunicationContacts");

                    b.Navigation("ComplianceDate")
                        .IsRequired();

                    b.Navigation("MsicCodes");

                    b.Navigation("OfficialContacts");

                    b.Navigation("Owners");

                    b.Navigation("StrikeOffSubmission")
                        .IsRequired();

                    b.Navigation("SystemAuditLogs");

                    b.Navigation("UserCompanyDepartments");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyWorkAssignment", b =>
                {
                    b.Navigation("AccountPlannedMonths");

                    b.Navigation("AssignedUsers");

                    b.Navigation("AuditPlannedMonths");

                    b.Navigation("Progress");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.MsicCode", b =>
                {
                    b.Navigation("CompanyLinks");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.User", b =>
                {
                    b.Navigation("AssignedDepartmentTasks");

                    b.Navigation("CompanyDepartments");

                    b.Navigation("ScheduledJobs");

                    b.Navigation("SystemAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
