// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWSA.MvcPortal.Persistence;

#nullable disable

namespace SWSA.MvcPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717052050_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ClientWorkAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuditStatus")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyActivityLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceScope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientWorkAllocations");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.BaseClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearEndMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CommunicationContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CommunicationContacts");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyMsicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("MsicCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MsicCodeId");

                    b.ToTable("CompanyMsicCodes");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICOrPassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePerIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresFormBESubmission")
                        .HasColumnType("bit");

                    b.Property<string>("TaxReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("CompanyOwners");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BagOrBoxCount")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentFlow")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("HandledByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("HandledByStaffId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.MsicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryReferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MsicCodes");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.OfficialContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("OfficialContacts");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ScheduledJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastExecuteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TriggerTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobKey");

                    b.HasIndex("UserId");

                    b.HasIndex("JobGroup", "JobKey")
                        .IsUnique();

                    b.ToTable("ScheduledJobs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavigateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemNotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Channel");

                    b.HasIndex("CreatedAt", "TemplateCode");

                    b.ToTable("SystemNotificationLogs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("'StaffId-' + RIGHT('000000' + CAST([Id] AS VARCHAR), 6)", true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForYear")
                        .HasColumnType("int");

                    b.Property<string>("InternalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceScope")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("WorkAssignments");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentUserMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkAssignmentId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkAssignmentUserMappings");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBacklog")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJobCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProgressNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeTakenInDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkAssignmentId")
                        .IsUnique();

                    b.ToTable("WorkProgresses");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.BaseCompany", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.Clients.BaseClient");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("EmployerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BaseCompanies", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.IndividualClient", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.Clients.BaseClient");

                    b.Property<string>("ICOrPassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IndividualClients", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.AnnualReturnWorkAssignment", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.WorkAssignment");

                    b.Property<DateTime?>("ARDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnniversaryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfAnnualReturn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturnedByClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSentToClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetedARDate")
                        .HasColumnType("datetime2");

                    b.ToTable("AnnualReturnWorkAssignments", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.AuditWorkAssignment", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.WorkAssignment");

                    b.Property<DateTime?>("AccDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstYearAccountStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonForLate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetedCirculation")
                        .HasColumnType("datetime2");

                    b.ToTable("AuditWorkAssignments", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.LLPWorkAssignment", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.WorkAssignment");

                    b.Property<DateTime?>("ARDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ARSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturnedByClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSentToClient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SSMExtensionDateForAcc")
                        .HasColumnType("datetime2");

                    b.ToTable("LLPWorkAssignments", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.StrikeOffWorkAssignment", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.WorkAssignment");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IRBSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SSMStrikeOffDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SSMSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("StrikeOffWorkAssignments", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.EnterpriseClient", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.Clients.BaseCompany");

                    b.ToTable("EnterpriseClients", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.LLPClient", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.Clients.BaseCompany");

                    b.ToTable("LLPClients", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.SdnBhdClient", b =>
                {
                    b.HasBaseType("SWSA.MvcPortal.Entities.Clients.BaseCompany");

                    b.ToTable("SdnBhdClients", (string)null);
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ClientWorkAllocation", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", "Client")
                        .WithMany("WorkAllocations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CommunicationContact", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", "Client")
                        .WithMany("CommunicationContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyMsicCode", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseCompany", "Company")
                        .WithMany("MsicCodes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.MsicCode", "MsicCode")
                        .WithMany("CompanyLinks")
                        .HasForeignKey("MsicCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("MsicCode");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.CompanyOwner", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseCompany", "Company")
                        .WithMany("Owners")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.DocumentRecord", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.User", "HandledByStaff")
                        .WithMany()
                        .HasForeignKey("HandledByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("HandledByStaff");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.OfficialContact", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", "Client")
                        .WithMany("OfficialContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.ScheduledJob", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "User")
                        .WithMany("ScheduledJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "PerformedByUser")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignmentUserMapping", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.User", "User")
                        .WithMany("AssignedWorks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", "WorkAssignment")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkProgress", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", "WorkAssignment")
                        .WithOne("Progress")
                        .HasForeignKey("SWSA.MvcPortal.Entities.WorkProgress", "WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.BaseCompany", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.Clients.BaseCompany", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.IndividualClient", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseClient", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.Clients.IndividualClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.AnnualReturnWorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.WorkAssignments.AnnualReturnWorkAssignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.AuditWorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.WorkAssignments.AuditWorkAssignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.LLPWorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.WorkAssignments.LLPWorkAssignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignments.StrikeOffWorkAssignment", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.WorkAssignment", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.WorkAssignments.StrikeOffWorkAssignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.EnterpriseClient", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseCompany", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.Clients.EnterpriseClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.LLPClient", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseCompany", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.Clients.LLPClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.SdnBhdClient", b =>
                {
                    b.HasOne("SWSA.MvcPortal.Entities.Clients.BaseCompany", null)
                        .WithOne()
                        .HasForeignKey("SWSA.MvcPortal.Entities.Clients.SdnBhdClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.BaseClient", b =>
                {
                    b.Navigation("CommunicationContacts");

                    b.Navigation("OfficialContacts");

                    b.Navigation("WorkAllocations");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.MsicCode", b =>
                {
                    b.Navigation("CompanyLinks");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.User", b =>
                {
                    b.Navigation("AssignedWorks");

                    b.Navigation("ScheduledJobs");

                    b.Navigation("SystemAuditLogs");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.WorkAssignment", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("SWSA.MvcPortal.Entities.Clients.BaseCompany", b =>
                {
                    b.Navigation("MsicCodes");

                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
