using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.SystemInfra;

// <auto-generated />
public class SystemNotificationLogMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<SystemNotificationLog, SystemNotificationLog>();
    }
}
        