using SWSA.MvcPortal.Dtos.Requests.Submission;
using SWSA.MvcPortal.Models.Submissions;

namespace SWSA.MvcPortal.Services.Interfaces.Submission;
// <auto-generated />
public interface IAnnualReturnSubmissionService
{
    // Define your method here
    Task<AnnualReturnSubmissionVM> GetARSubmissionVMByIdAsync(int submissionId);
    Task<List<AnnualReturnSubmissionVM>> GetARSubmissionVMsAsync();
    Task<int> RequestSubmissionForCompany(int companyId);
    Task<bool> UpdateSubmissionForCompany(EditARSubmissionRequest req);
}
