using SWSA.MvcPortal.Dtos.Requests.Submission;
using SWSA.MvcPortal.Models.Submissions;

namespace SWSA.MvcPortal.Services.Interfaces.Submission;

// <auto-generated />
public interface IAuditSubmissionService
{
    Task<AuditSubmissionVM> GetAuditSubmissionVMByIdAsync(int submissionId);

    // Define your method here
    Task<List<AuditSubmissionVM>> GetAuditSubmissionVMsAsync();
    Task<int> RequestSubmissionForCompany(int companyId);
    Task<bool> UpdateSubmissionForCompany(EditAuditSubmissionRequest req);
}