using SWSA.MvcPortal.Dtos.Requests.Submission;
using SWSA.MvcPortal.Models.Submissions;

namespace SWSA.MvcPortal.Services.Interfaces.Submission;
// <auto-generated />
public interface ICompanyStrikeOffSubmissionService
{
    Task<CompanyStrikeOffSubmissionVM> GetStrikeOffSubmissionVMByIdAsync(int submissionId);

    // Define your method here
    Task<List<CompanyStrikeOffSubmissionVM>> GetStrikeOffSubmissionVMsAsync();
    Task<int> RequestSubmissionForCompany(SubmissionRequest req);
    Task<bool> UpdateSubmissionForCompany(EditCompanyStrikeOffSubmissionRequest req);
}
