using SWSA.MvcPortal.Dtos.Requests.Submission;
using SWSA.MvcPortal.Models.Submissions;

namespace SWSA.MvcPortal.Services.Interfaces.Submission;

// <auto-generated />
public interface ILLPSubmissionService
{
    Task<LLPSubmissionVM> GetLLPSubmissionVMByIdAsync(int submissionId);

    // Define your method here
    Task<List<LLPSubmissionVM>> GetLLPSubmissionVMsAsync();
    Task<int> RequestSubmissionForCompany(SubmissionRequest req);
    Task<bool> UpdateSubmissionForCompany(EditLLPSubmissionRequest req);
}