using SWSA.MvcPortal.Repositories.Interfaces;
using AutoMapper;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Services.Interfaces.Clients;

namespace SWSA.MvcPortal.Services.Clients;

// <auto-generated />
public class CommunicationContactService(
IMapper mapper,
IUserContext userContext,
ICommunicationContactRepository repo,
ISystemAuditLogService sysAuditService
) : ICommunicationContactService
{
    #region VM/DTO Query Method 
    #endregion

    public async Task<int> Create(CreateCompanyCommunicationContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }
        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = mapper.Map<CommunicationContact>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data.Id.ToString(), $"Company communication: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> Edit(EditCompanyCommunicationContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }
        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = await repo.GetByIdAsync(req.ContactId);

        Guard.AgainstNullData(data, "Company Staff not found");

        if (data!.ClientId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.ContactName = req.ContactName;
        data.WhatsApp = req.WhatsApp;
        data.Email = req.Email;
        data.Remark = req.Remark;
        data.Position = req.Position;

        repo.Update(data);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data.Id.ToString(), $"Company communication contact: {data.ContactName}", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> Delete(int id)
    {
        var data = await repo.GetByIdAsync(id);

        Guard.AgainstNullData(data, "Company Staff not found");
        Guard.AgainstUnauthorizedCompanyAccess(data.ClientId, null, userContext);

        repo.Remove(data!);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data!.ClientId.ToString(), $"Company communication contact: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

}