using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Contacts;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Entities.Clients;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Persistence.QueryExtensions;
using SWSA.MvcPortal.Services.Interfaces.Clients;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.Clients;

// <auto-generated />
public class CommunicationContactService(
ISystemAuditLogService sysAuditService,
AppDbContext db
) : ICommunicationContactService
{
    private readonly DbSet<BaseClient> _clients = db.Set<BaseClient>();

    private readonly DbSet<CommunicationContact> _contact = db.Set<CommunicationContact>();

    #region Get Data
    public async Task<CommunicationContact?> GetByIdAsync(int id)
    {
        var data = await _contact.FirstOrDefaultAsync(c => c.Id == id);
        return data;
    }

    #endregion
    public async Task<bool> Delete(int id)
    {
        var data = await GetByIdAsync(id);
        Guard.AgainstNullData(data, "Communication Contact not found");

        db.Remove(data!);
        await db.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CommunicationContact, data!.ClientId.ToString(), $"Company communication contact: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<CommunicationContact> UpsertContact(UpsertCommunicationContactRequest req)
    {
        var clientExist = await _clients.ExistsAsync(req.ClientId);
        Guard.AgainstNotExist(clientExist, "Client Not Found : " + req.ClientId);

        CommunicationContact? entity = null;
        if (req.Id.HasValue)
        {
            entity = await _contact.FirstOrDefaultAsync(c => c.Id == req.Id.Value);
        }

        if (entity != null)
        {
            entity.ContactName = req.Name;
            entity.WhatsApp = req.Phone;
            entity.Email = req.Email;
            entity.Position = req.Position;
            entity.Remark = req.Remark;
            _contact.Update(entity);
        }
        else
        {
            entity = new CommunicationContact
            {
                ClientId = req.ClientId,
                ContactName = req.Name,
                WhatsApp = req.Phone,
                Email = req.Email,
                Position = req.Position,
                Remark = req.Remark
            };
            await _contact.AddAsync(entity);
        }

        await db.SaveChangesAsync();
        return entity;
    }
}