using Force.DeepCloner;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Contacts;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Entities.Clients;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Persistence.QueryExtensions;
using SWSA.MvcPortal.Services.Interfaces.Clients;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.Clients;

// <auto-generated />
public class CommunicationContactService(
ISystemAuditLogService sysAuditService,
AppDbContext db
) : ICommunicationContactService
{
    private readonly DbSet<BaseClient> _clients = db.Set<BaseClient>();

    private readonly DbSet<CommunicationContact> _contact = db.Set<CommunicationContact>();

    #region Get Data
    public async Task<CommunicationContact?> GetByIdAsync(int id)
    {
        var data = await _contact.FirstOrDefaultAsync(c => c.Id == id);
        return data;
    }

    #endregion

    public async Task<CommunicationContact> UpsertContact(UpsertCommunicationContactRequest req)
    {
        var clientExist = await _clients.ExistsAsync(req.ClientId);
        Guard.AgainstNotExist(clientExist, "Client Not Found : " + req.ClientId);

        CommunicationContact? entity = null;
        if (req.Id.HasValue)
        {
            entity = await _contact.FirstOrDefaultAsync(c => c.Id == req.Id.Value);
        }

        SystemAuditLogEntry? log = null;
        if (entity != null)
        {
            var oldData = entity.DeepClone();
            entity.UpdateInfo(req.Name, req.Phone, req.Email, req.Position, req.Remark);
            _contact.Update(entity);
            log = SystemAuditLogEntry.Update(SystemAuditModule.CommunicationContact, entity.Id.ToString(), $"Contact: {entity.ContactName}", oldData, entity);
        }
        else
        {
            entity = new CommunicationContact
            {
                ClientId = req.ClientId,
                ContactName = req.Name,
                WhatsApp = req.Phone,
                Email = req.Email,
                Position = req.Position,
                Remark = req.Remark
            };
            await _contact.AddAsync(entity);
        }

        await db.SaveChangesAsync();

        log ??= SystemAuditLogEntry.Create(SystemAuditModule.CommunicationContact, entity.Id.ToString(), $"Contact: {entity.ContactName}", entity);
        sysAuditService.LogInBackground(log);

        return entity;
    }

    public async Task<bool> Delete(int id)
    {
        var data = await GetByIdAsync(id);
        Guard.AgainstNullData(data, "Communication Contact not found");

        db.Remove(data);
        await db.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(SystemAuditModule.CommunicationContact, data!.Id.ToString(), $"Contact: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }
}