using AutoMapper;
using Force.DeepCloner;
using Microsoft.EntityFrameworkCore;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Dtos.Requests.Contacts;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Entities.Clients;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Persistence;
using SWSA.MvcPortal.Persistence.QueryExtensions;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.Clients;

// <auto-generated />
public class OfficialContactService(
IMapper mapper,
IUserContext userContext,
IOfficialContactRepository repo,
ISystemAuditLogService sysAuditService,
AppDbContext db
) : IOfficialContactService
{
    private readonly DbSet<BaseClient> _clients = db.Set<BaseClient>();

    private readonly DbSet<OfficialContact> _contact = db.Set<OfficialContact>();
    #region VM/DTO Query Method 

    public async Task<OfficialContact?> GetByIdAsync(int id)
    {
        var data = await _contact.FirstOrDefaultAsync(c => c.Id == id);
        return data;
    }

    #endregion

    public async Task<OfficialContact> UpsertContact(UpsertOfficialContactRequest req)
    {
        var clientExist = await _clients.ExistsAsync(req.ClientId);
        Guard.AgainstNotExist(clientExist, "Client Not Found : " + req.ClientId);

        OfficialContact? entity = null;
        if (req.Id.HasValue)
        {
            entity = await _contact.FirstOrDefaultAsync(c => c.Id == req.Id.Value);
        }

        if (entity != null)
        {
            entity.Address = req.Address;
            entity.OfficeTel = req.Phone;
            entity.Email = req.Email;
            entity.Remark = req.Remark;
            _contact.Update(entity);
        }
        else
        {
            entity = new OfficialContact
            {
                ClientId = req.ClientId,
                Address = req.Address,
                OfficeTel = req.Phone,
                Email = req.Email,
                Remark = req.Remark,
            };
            await _contact.AddAsync(entity);
        }

        await db.SaveChangesAsync();
        return entity;
    }

    public async Task<bool> Delete(int id)
    {
        var data = await GetByIdAsync(id);
        Guard.AgainstNullData(data, "Company Official Contact not found");

        db.Remove(data!);
        await db.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.OfficialContact, data.ClientId.ToString(), $"Company Official Contact", data);
        sysAuditService.LogInBackground(log);
        return true;
    }
}