using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Users;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Models.Users;
using AutoMapper;
using Force.DeepCloner;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Services.Interfaces.UserAccess;

namespace SWSA.MvcPortal.Services.UserAccess;

// <auto-generated />
public class UserService(
IUserRepository repo,
IMapper mapper,
ISystemAuditLogService sysAuditService,
IUserContext userContext) : IUserService
{
    #region VM/DTO Query Method 
    public async Task<List<UserListVM>> GetUsersAsync()
    {
        var data = await repo.GetAllAsync();

        return mapper.Map<List<UserListVM>>(data);
    }

    public async Task<List<UserSelectionVM>> GetUserSelectionAsync()
    {
        List<User> data = userContext.IsSuperAdmin
            ? await repo.GetByActiveStatus(true)
            : [await repo.GetByIdAsync(userContext.EntityId)];

        return mapper.Map<List<UserSelectionVM>>(data);
    }

    public async Task<UserOverviewVM> GetUserOverviewVMAsync(string staffId)
    {
        var data = await repo.GetOverviewVMByStaffIdAsync(staffId);
        Guard.AgainstNullData(data, "User not found");
        data.MergeCompany();
        return data;
    }

    public async Task<UserVM> GetUserByIdAsync(string staffId)
    {
        var data = await repo.GetByStaffIdAsync(staffId);
        Guard.AgainstNullData(data, "User not found");

        return mapper.Map<UserVM>(data);
    }
    #endregion

    public async Task<string> Create(CreateUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        if (await repo.ExistsByUsernameAsync(req.Username))
        {
            throw new BusinessLogicException("Username already exists");
        }

        var user = mapper.Map<User>(req);
        user.SetAndHashPassword(req.Password);

        repo.Add(user);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.User, user.StaffId.ToString(), $"User: {user.FullName}", user);
        sysAuditService.LogInBackground(log);
        return user.StaffId;
    }

    public async Task<bool> Edit(EditUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        var user = await repo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");

        //User cannot edit own role
        if (user.StaffId == userContext.StaffId && req.Role != user.Role)
            throw new BusinessLogicException("You cannot edit your own role");

        var oldData = user.DeepClone();

        user.FullName = req.FullName;
        user.Email = req.Email;
        user.PhoneNumber = req.PhoneNumber;
        user.IsActive = req.IsActive;
        user.Role = req.Role;

        if (!string.IsNullOrEmpty(req.Password))
        {
            user.SetAndHashPassword(req.Password);
        }

        repo.Update(user);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.User, user.StaffId.ToString(), $"User: {user.FullName}", oldData, user);
        sysAuditService.LogInBackground(log);

        return true;
    }

    public async Task<UserVM> DeleteUserByIdAsync(string staffId)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        var data = await repo.GetByStaffIdAsync(staffId);
        Guard.AgainstNullData(data, "User not found");

        if (data.StaffId == userContext.StaffId)
            throw new BusinessLogicException("You cannot delete yourself");

        repo.Remove(data!);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.User, data!.StaffId.ToString(), $"User: {data.FullName}", data);
        sysAuditService.LogInBackground(log);

        return mapper.Map<UserVM>(data);
    }
}