using SWSA.MvcPortal.Repositories.Interfaces;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Dtos.Requests.Users;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Models.Users;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;
using SWSA.MvcPortal.Services.Interfaces.UserAccess;

namespace SWSA.MvcPortal.Services.UserAccess;

// <auto-generated />
public class UserCompanyDepartmentService(
IMemoryCache cache,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
IUserCompanyDepartmentRepository repo,
IUserRepository userRepo,
ICompanyRepository companyRepo
    ) : IUserCompanyDepartmentService
{
    #region VM/DTO Query Method 
    #endregion


    public async Task<string> Create(int companyId, CreateUserCompanyDepartmentRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }

        Guard.AgainstNotSuperAdmin(userContext);
        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");
        var cp = await companyRepo.GetByIdAsync(req.CompanyId);
        Guard.AgainstNullData(cp, "Company not found");

        var departments = GetDepartments();

        var existing = await repo.GetByCompanyIdAndStaffId(companyId, req.StaffId);
        if (existing.Count > 0)
        {
            throw new BusinessLogicException("The user is already assigned to this company. Please use the update function instead of create.");
        }

        var newEntities = UserCompanyDepartmentMapper.ToEntities(req.Departments, companyId, user.Id);
        repo.AddRange(newEntities);
        await repo.SaveChangesAsync();

        ClearCompaniesCache(companyId);

        var deptNamesNew = newEntities.Select(e => e.Department).Where(e => departments.Contains(e)).ToList();
        var newObject = new UserCompanyDepartmentAuditVM(deptNamesNew);

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.Company, companyId.ToString(), $"Assigned handle user {user.FullName}", newObject);
        sysAuditService.LogInBackground(log);

        return req.StaffId;
    }

    public async Task<bool> Edit(int companyId, EditUserCompanyDepartment req)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");
        var cp = await companyRepo.GetByIdAsync(req.CompanyId);
        Guard.AgainstNullData(cp, "Company not found");

        var departments = GetDepartments();

        var existing = await repo.GetByCompanyIdAndStaffId(companyId, req.StaffId);
        var existingDepts = existing.Select(e => e.Department).ToHashSet();
        var reqDepts = req.Departments.Distinct().ToHashSet();

        var newDepts = req.Departments.Where(name => !existingDepts.Contains(name)).Distinct().ToList();
        var newEntities = UserCompanyDepartmentMapper.ToEntities(newDepts, companyId, user.Id);
        var removeEntities = existing.Where(e => !reqDepts.Contains(e.Department)).ToList();

        //If no remove / add, return true, do not process to log and save
        if (newEntities.Count == 0 && removeEntities.Count == 0)
        {
            return true;
        }

        if (removeEntities.Count != 0)
        {
            repo.RemoveRange(removeEntities);
        }

        if (newEntities.Count != 0)
        {
            repo.AddRange(newEntities);
        }

        await repo.SaveChangesAsync();

        ClearCompaniesCache(companyId);

        var deptNamesOld = existing.Select(e => e.Department).Where(name => departments.Contains(name)).ToList();
        var deptNamesNew = reqDepts.Where(name => departments.Contains(name)).ToList();

        var oldObject = new UserCompanyDepartmentAuditVM(deptNamesOld);
        var newObject = new UserCompanyDepartmentAuditVM(deptNamesNew);

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.Company, companyId.ToString(), $"Update handle user {user.FullName}", oldObject, newObject);
        sysAuditService.LogInBackground(log);

        return true;
    }

    public async Task<bool> Delete(int companyId, string staffId)
    {
        Guard.AgainstNotSuperAdmin(userContext);
        var user = await userRepo.GetByStaffIdAsync(staffId);
        Guard.AgainstNullData(user, "User not found");


        var existing = await repo.GetByCompanyIdAndStaffId(companyId, staffId);
        var departmentNames = existing.Select(e => e.Department).ToList();
        var oldObject = new UserCompanyDepartmentAuditVM(departmentNames);

        if (existing.Count > 0)
        {
            repo.RemoveRange(existing);
            await repo.SaveChangesAsync();
        }
        ClearCompaniesCache(companyId);

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.Company, companyId.ToString(), $"Removed handle user {user.FullName}", oldObject);
        sysAuditService.LogInBackground(log);

        return true;
    }

    private void ClearCompaniesCache(int? id = 0)
    {
        string cacheKey = $"{DataCacheKey.Companies}";
        cache.Remove(cacheKey);
        if (id.HasValue && id > 0)
        {
            cache.Remove($"{cacheKey}_{id}");
            cache.Remove($"{cacheKey}_{id}_Details");
        }
    }

    private List<string> GetDepartments()
    {
        return new List<string>
        {
            DepartmentType.Audit,
            DepartmentType.Account,
            DepartmentType.Secretary,
            DepartmentType.Tax
        };
    }
}