using SWSA.MvcPortal.Dtos.Requests.SchedulerJobs;
using SWSA.MvcPortal.Models.ScheduledJobs;

namespace SWSA.MvcPortal.Services.Interfaces.Scheduler;
// <auto-generated />
public interface IScheduledJobService
{
    Task<bool> ExecuteByJobKey(string jobKey);
    Task<List<ScheduledJobVM>> GetAllScheduledJobs();
    Task<ScheduledJobVM> GetScheduledJobByJobKey(string jobKey);

    Task<bool> UpdateScheduleJob(UpdateScheduleJobRequest req);

    // Define your method here
    Task UpdateExecuteTimeAsync(string jobkey);
    Task<string> CreateScheduleJob(CreateScheduleJobRequest req);
    Task<bool> DeleteByJobKey(string jobKey);
}
