using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Services;

// <auto-generated />
public class AuditSubmissionService(
    IAuditSubmissionRepository repo
) : IAuditSubmissionService
{
    #region VM/DTO Query Method 
    #endregion
}