

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyWorkAssignmentService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyWorkAssignmentRepository repo,
ICompanyStaffRepository companyStaffRepo
    ) : ICompanyWorkAssignmentService
{

    public async Task<List<CompanyWorkListVM>> GetWorkAssignments()
    {
        var data = (await repo.GetAllAsync()).ToList();
        return mapper.Map<List<CompanyWorkListVM>>(data);
    }

    public async Task<CompanyWorkVM> GetWorkAssignmentById(int taskId)
    {
        var data = await repo.GetWithIncludedByIdAsync(taskId);
        Guard.AgainstNullData(data, "Company Work Assignment not found");

        return mapper.Map<CompanyWorkVM>(data);
    }

    public async Task<int> CreateCompanyWorkAssignment(CreateCompanyWorkAssignmentRequest req)
    {
        var staff = await companyStaffRepo.GetByStaffId(req.AssignedStaffId);
        Guard.AgainstNullData(staff, "Company Staff not found");

        var entity = mapper.Map<CompanyWorkAssignment>(req);
        if (entity.Progress == null)
        {
            entity.Progress = new CompanyWorkProgress();
        }

        entity.AssignedStaffId = staff.Id;
        repo.Add(entity);
        await repo.SaveChangesAsync();

        return entity.Id;
    }

    public async Task<bool> EditCompanyWorkAssignment(EditCompanyWorkAssignmentRequest req)
    {
        var task = await repo.GetByIdAsync(req.TaskId);
        Guard.AgainstNullData(task, "Company Work Assignment not found");

        var reqStaff = await companyStaffRepo.GetByStaffId(req.AssignedStaffId);
        Guard.AgainstNullData(reqStaff, "Company Staff not found");

        //update if transfer to another staff  
        if (task!.AssignedStaffId != reqStaff.Id)
        {
            task.AssignedStaffId = reqStaff.Id;
        }

        task.CompanyActivityLevel = req.CompanyActivityLevel;
        task.WorkType = req.WorkType;
        task.ServiceScope = req.ServiceScope;
        task.YearToDo = req.YearToDo;
        task.MonthToDo = req.MonthToDo;
        task.InternalNote = req.InternalNote;
        task.IsCompleted = req.IsCompleted;
        task.CompletedDate = req.CompletedDate ?? null;
        task.UpdatedAt = DateTime.Now;

        repo.Update(task);
        await repo.SaveChangesAsync();

        return true;
    }

    public async Task<CompanyWorkAssignment> DeleteWork(int taskId)
    {
        var data = await repo.GetByIdAsync(taskId);
        Guard.AgainstNullData(data, "Company Work Assignment not found");

        repo.Remove(data!);

        await repo.SaveChangesAsync();
        return data!;
    }

}
