
// <auto-generated />

using AutoMapper;
using Force.DeepCloner;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Helpers;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompanyStaffs;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Models.Users;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using System.ComponentModel.Design;

namespace SWSA.MvcPortal.Services;

public class CompanyCommunicationContactService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ICompanyCommunicationContactRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyCommunicationService
{
    public async Task<List<CompanyCommunicationContactVM>> GetCommunicationContactsByCompanyId(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);

        var data = await repo.GetAllByCompanyIdAsync(companyId);
        return mapper.Map<List<CompanyCommunicationContactVM>>(data); ;
    }

    public async Task<int> Create(CreateCompanyCommunicationContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }
        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = mapper.Map<CompanyCommunicationContact>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data.Id.ToString(), $"Company communication: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> Edit(EditCompanyCommunicationContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }
        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = await repo.GetByIdAsync(req.ContactId);

        Guard.AgainstNullData(data, "Company Staff not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.ContactName = req.ContactName;
        data.WhatsApp = req.WhatsApp;
        data.Email = req.Email;
        data.Remark = req.Remark;
        data.Position = req.Position;

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data.Id.ToString(), $"Company communication contact: {data.ContactName}", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> Delete(int id)
    {
        var data = await repo.GetByIdAsync(id);

        Guard.AgainstNullData(data, "Company Staff not found");
        Guard.AgainstUnauthorizedCompanyAccess(data.CompanyId, null, userContext);

        repo.Remove(data!);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data!, true);

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyCommunicationContact, data!.CompanyId.ToString(), $"Company communication contact: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    private void UpdateCompanyCommunicationContactCache(CompanyCommunicationContact contact, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{contact.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }
}
