using System.Threading.Tasks;
using AutoMapper;
using Force.DeepCloner;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyWorkProgressService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyWorkProgressRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyWorkProgressService
{

    public async Task<bool> EditCompanyWorkProgress(EditCompanyWorkProgressRequest req)
    {
        var progress = await repo.GetByIdAsync(req.ProgressId);
        Guard.AgainstNullData(progress, "Work Progress not found.");

        var oldData = progress.DeepClone();

        progress!.StartDate = req.StartDate;
        progress.EndDate = req.EndDate;
        progress.TimeTakenInDays = req.TimeTakenInDays;
        progress.Status = req.Status;
        progress.ProgressNote = req.ProgressNote;
        progress.UpdatedAt = DateTime.Now;

        repo.Update(progress);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyWorkAssignment, progress.WorkAssignmentId.ToString(), $"Work Assignment Progress", oldData, progress);
        sysAuditService.LogInBackground(log);
        return true;
    }

}
