using System.Threading.Tasks;
using AutoMapper;
using Force.DeepCloner;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Extensions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyWorkAssignmentService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ICompanyWorkAssignmentRepository repo,
ICompanyStaffRepository companyStaffRepo,
ISystemAuditLogService sysAuditService
    ) : ICompanyWorkAssignmentService
{
    public async Task<List<CompanyWorkListVM>> GetWorkAssignments()
    {
        var data = userContext.IsSuperAdmin? [.. await repo.GetAllAsync()]
            : await repo.GetByCompanyIds(userContext.AllowedCompanyIds);
        return mapper.Map<List<CompanyWorkListVM>>(data);
    }

    public async Task<List<CompanyWorkCalendarVM>> GetWorkCalendarEvents()
    {
        var data = userContext.IsSuperAdmin ? [.. await repo.GetAllAsync()]
         : await repo.GetByCompanyIds(userContext.AllowedCompanyIds);
        return data.Select(CompanyWorkCalendarVM.FromTask).ToList();
    }

    public async Task<CompanyWorkVM> GetWorkAssignmentById(int taskId)
    {
        var data = await repo.GetWithIncludedByIdAsync(taskId);
        Guard.AgainstNullData(data, "Company Work Assignment not found");
        Guard.AgainstUnauthorizedCompanyAccess(data!.CompanyId,null, userContext);
        return mapper.Map<CompanyWorkVM>(data);
    }

    public async Task<int> CreateCompanyWorkAssignment(CreateCompanyWorkAssignmentRequest req)
    {
        Guard.AgainstUnauthorizedCompanyAccess(req!.CompanyId, null, userContext);

        var staff = await companyStaffRepo.GetByStaffId(req.AssignedStaffId);
        Guard.AgainstNullData(staff, "Company Staff not found");

        var entity = mapper.Map<CompanyWorkAssignment>(req);
        if (entity.Progress == null)
        {
            entity.Progress = new CompanyWorkProgress();
        }
        entity.AssignedStaffId = staff.Id;
        repo.Add(entity);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyWorkAssignment, entity.Id.ToString(), $"Company Work Assignment : {entity.WorkType.GetDisplayName()}", entity);
        sysAuditService.LogInBackground(log);
        return entity.Id;
    }

    public async Task<bool> EditCompanyWorkAssignment(EditCompanyWorkAssignmentRequest req)
    {

        var task = await repo.GetByIdAsync(req.TaskId);
        Guard.AgainstNullData(task, "Company Work Assignment not found");
        Guard.AgainstUnauthorizedCompanyAccess(task!.CompanyId, null, userContext);

        var reqStaff = await companyStaffRepo.GetByStaffId(req.AssignedStaffId);
        Guard.AgainstNullData(reqStaff, "Company Staff not found");

        //update if transfer to another staff  
        if (task!.AssignedStaffId != reqStaff.Id)
        {
            task.AssignedStaffId = reqStaff.Id;
        }

        var oldData = task.DeepClone();

        task.CompanyActivityLevel = req.CompanyActivityLevel;
        task.WorkType = req.WorkType;
        task.ServiceScope = req.ServiceScope;
        task.DueDate = req.DueDate;
        task.InternalNote = req.InternalNote;
        task.IsCompleted = req.IsCompleted;
        task.CompletedDate = req.CompletedDate ?? null;
        task.UpdatedAt = DateTime.Now;

        repo.Update(task);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyWorkAssignment, task.Id.ToString(), $"Company Work Assignment : {task.WorkType.GetDisplayName()}", oldData, task);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<CompanyWorkAssignment> DeleteWork(int taskId)
    {
        var data = await repo.GetByIdAsync(taskId);
        Guard.AgainstNullData(data, "Company Work Assignment not found");
        Guard.AgainstUnauthorizedCompanyAccess(data!.CompanyId, null, userContext);

        repo.Remove(data!);

        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyWorkAssignment, data!.Id.ToString(), $"Company Work Assignment : {data.WorkType.GetDisplayName()}", data);
        sysAuditService.LogInBackground(log);
        return data!;
    }
}
