

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyComplianceDateService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyComplianceDateRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyComplianceDateService
{

    public async Task<bool> SaveComplianceDate(EditCompanyComplianceDate req)
    {
        var data = await repo.GetByCompanyId(req.CompanyId);
        bool isNew = data == null;

        data ??= new CompanyComplianceDate();

        var oldData = mapper.Map<CompanyComplianceDate>(data);

        data.UpdateComplianceDates(req);

        if (isNew)
        {
            data.CompanyId = req.CompanyId;
            repo.Add(data);
        }
        else
        {
            data.AccountDueDate = req.AccountDueDate;
            data.AnniversaryDate = req.AnniversaryDate;
            data.AGMDate = req.AGMDate;
            data.AnnualReturnDueDate = req.AnnualReturnDueDate;
            data.FirstYearAccountStart = req.FirstYearAccountStart;
            data.Notes = req.Notes;
        }

        await repo.SaveChangesAsync();

        UpdateCompanyComplianceDateCache(data);
        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.Company, data.CompanyId.ToString(), "Company Compliance Date", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    private void UpdateCompanyComplianceDateCache(CompanyComplianceDate date, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{date.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }

}
