using AutoMapper;
using Force.DeepCloner;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyOfficialContactService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ICompanyOfficialContactRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyOfficialContactService
{
    public async Task<int> CreateContact(CreateCompanyOfficialContactRequest req)
    {
        if (!req.CompanyId.HasValue)
        {
            throw new BadHttpRequestException("CompanyId is required");
        }

        Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);

        var data = mapper.Map<CompanyOfficialContact>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data);

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> EditContact(EditCompanyOfficialContactRequest req)
    {
        if (req.CompanyId.HasValue)
        {
            Guard.AgainstUnauthorizedCompanyAccess((int)req.CompanyId, null, userContext);
        }

        var data = await repo.GetByIdAsync(req.ContactId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.Address = req.Address;
        data.OfficeTel = req.OfficeTel;
        data.Email = req.Email;
        data.Remark = req.Remark;

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data);

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> DeleteContact(int ownerId)
    {
        var data = await repo.GetByIdAsync(ownerId);
        Guard.AgainstNullData(data, "Company Official Contact not found");

        repo.Remove(data!);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data!, true);

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOfficialContact, data.CompanyId.ToString(), $"Company Official Contact", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    private void UpdateCompanyOfficialContactCache(CompanyOfficialContact contact, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{contact.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }
}
