
// <auto-generated />

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Repositories.Repo;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;

public class CompanyTypeService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyTypeRepository repo
    ) : ICompanyTypeService
{
    public async Task<List<CompanyType>> GetCompanyTypesAsync()
    {
        return await GetCompanyTypesFromCacheAsync();
    }

    private async Task<List<CompanyType>> GetCompanyTypesFromCacheAsync()
    {
        if (cache.TryGetValue(DataCacheKey.CompanyTypes, out List<CompanyType>? cpTypes))
        {
            return cpTypes ?? [];
        }

        // Fetch data from the database or any other source
        cpTypes = [.. await repo.GetAllAsync()];
        cache.Set(DataCacheKey.CompanyTypes, cpTypes, cacheOptions);
        return cpTypes;
    }

}
