
// <auto-generated />

using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Helpers;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompanyStaffs;
using SWSA.MvcPortal.Models.Users;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using System.ComponentModel.Design;

namespace SWSA.MvcPortal.Services;

public class CompanyStaffService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IHttpContextAccessor httpContextAccessor,
IUserContext userContext,
ICompanyStaffRepository repo
    ) : ICompanyStaffService
{
    private readonly ISession _session =
   httpContextAccessor.HttpContext?.Session
   ?? throw new InvalidOperationException("Session is not available.");
    public async Task<CompanyStaffVM> GetStaffByStaffId(string staffId)
    {
        var data = await repo.GetByStaffId(staffId);
        Guard.AgainstNullData(data, "Company staff not found");
        Guard.AgainstCrossCompanyAccess(data.CompanyId, userContext);

        return mapper.Map<CompanyStaffVM>(data);
    }

    public async Task<List<CompanyStaffVM>> GetStaffsByCompanyId(int companyId)
    {
        Guard.AgainstCrossCompanyAccess(companyId, userContext);

        var data = await repo.GetAllByCompanyIdAsync(companyId);
        return mapper.Map<List<CompanyStaffVM>>(data); ;
    }

    public async Task<int> CreateContact(CreateCompanyStaffRequest req)
    {
        var data = mapper.Map<CompanyStaff>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);
        return data.Id;
    }

    public async Task<bool> EditContact(EditCompanyStaffInfoRequest req)
    {
        var data = await repo.GetByStaffId(req.StaffId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        data.CompanyDepartmentId = req.CompanyDepartmentId;
        data.ContactName = req.ContactName;
        data.WhatsApp = req.WhatsApp;
        data.Email = req.Email;
        data.Remark = req.Remark;
        data.Position = req.Position;

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);
        return true;
    }

    public async Task<bool> EditLoginProfile(EditCompanyStaffLoginProfileRequest req)
    {
        var data = await repo.GetByStaffId(req.StaffId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (req.EnableLogin)
        {
            if (string.IsNullOrEmpty(req.Username) || string.IsNullOrEmpty(req.Password))
                throw new BusinessLogicException("Username and password cannot be empty");

            if (await repo.ExistUsernameInCompanyExcludingStaffId(data.CompanyId, req.Username, data.StaffId))
                throw new BusinessLogicException("Username already exists");

            data.IsLoginEnabled = true;
            data.Username = req.Username;
            if (!string.IsNullOrEmpty(req.Password) && req.Password != AppSettings.DisplayPassword)
                data.HashedPassword = PasswordHasher.Hash(req.Password);
        }
        else
        {
            data.IsLoginEnabled = false;
        }

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);
        return true;
    }

    public async Task<bool> DeleteContact(string staffId)
    {
        var data = await repo.GetByStaffId(staffId);
        Guard.AgainstNullData(data, "Company Communication Contact not found");

        repo.Remove(data!);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data!, true);
        return true;
    }

    private void UpdateCompanyCommunicationContactCache(CompanyStaff contact, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{contact.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }

    public async Task<bool> SetStaffSession(string staffId)
    {
        var staff = await repo.GetByStaffId(staffId);
        if (staff == null)
        {
            return false;
        }

        var staffVM = mapper.Map<CompanyStaffVM>(staff);

        _session.SetString(SessionKeys.StaffId, staff.StaffId);
        _session.SetString(SessionKeys.CompanyId, staff.CompanyId.ToString());
        if (staff.CompanyDepartmentId.HasValue)
        {
            _session.SetString(SessionKeys.CompanyDepartmentId, staff.CompanyDepartmentId.ToString() ?? "");
        }
        _session.SetString(SessionKeys.Name, staffVM.ContactName);
        _session.SetString(SessionKeys.LoginTime, DateTime.Now.ToString());
        return true;
    }

}
