

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class CompanyComplianceDateService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyComplianceDateRepository repo
    ) : ICompanyComplianceDateService
{

    public async Task<bool> SaveComplianceDate(EditCompanyComplianceDate req)
    {
        var data = await repo.GetByCompanyId(req.CompanyId);
        bool isNew = data == null;

        data ??= new CompanyComplianceDate();
        data.UpdateComplianceDates(req);

        if (isNew)
        {
            data.CompanyId = req.CompanyId;
            repo.Add(data);
        }
        else
        {
            repo.Update(data);
        }

        await repo.SaveChangesAsync();

        UpdateCompanyComplianceDateCache(data);
        return true;
    }

    private void UpdateCompanyComplianceDateCache(CompanyComplianceDate date, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{date.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }

}
