
// <auto-generated />

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;

public class CompanyOfficialContactService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
ICompanyOfficialContactRepository repo
    ) : ICompanyOfficialContactService
{
    public async Task<int> CreateContact(CreateCompanyOfficialContactRequest req)
    {
        var data = mapper.Map<CompanyOfficialContact>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data);
        return data.Id;
    }

    public async Task<bool> EditContact(EditCompanyOfficialContactRequest req)
    {
        var data = await repo.GetByIdAsync(req.ContactId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        data.Address = req.Address;
        data.OfficeTel = req.OfficeTel;
        data.Email = req.Email;
        data.Remark = req.Remark;

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data);
        return true;
    }

    public async Task<bool> DeleteContact(int ownerId)
    {
        var data = await repo.GetByIdAsync(ownerId);
        Guard.AgainstNullData(data, "Company Official Contact not found");

        repo.Remove(data!);
        await repo.SaveChangesAsync();
        UpdateCompanyOfficialContactCache(data!, true);
        return true;
    }

    private void UpdateCompanyOfficialContactCache(CompanyOfficialContact contact, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{contact.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }
}
