
// <auto-generated />

using AutoMapper;
using Force.DeepCloner;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Exceptions;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Helpers;
using SWSA.MvcPortal.Dtos.Requests.Companies;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompanyStaffs;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Models.Users;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using System.ComponentModel.Design;

namespace SWSA.MvcPortal.Services;

public class CompanyStaffService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ICompanyStaffRepository repo,
ISystemAuditLogService sysAuditService
    ) : ICompanyStaffService
{
    public async Task<CompanyStaffVM> GetStaffByStaffId(string staffId)
    {
        var data = await repo.GetByStaffId(staffId);
        Guard.AgainstNullData(data, "Company staff not found");

        return mapper.Map<CompanyStaffVM>(data);
    }

    public async Task<List<CompanyStaffVM>> GetStaffsByCompanyId(int companyId)
    {
        var data = await repo.GetAllByCompanyIdAsync(companyId);
        return mapper.Map<List<CompanyStaffVM>>(data); ;
    }

    public async Task<int> CreateStaff(CreateCompanyStaffRequest req)
    {
        var data = mapper.Map<CompanyStaff>(req);
        repo.Add(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyStaff, data.CompanyId.ToString(), $"Company staff login profile: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return data.Id;
    }

    public async Task<bool> EditStaff(EditCompanyStaffInfoRequest req)
    {
        var data = await repo.GetByStaffId(req.StaffId);

        Guard.AgainstNullData(data, "Company Official Contact not found");

        if (data!.CompanyId != req.CompanyId)
        {
            return false;
        }

        var oldData = data.DeepClone();
        data.CompanyDepartmentId = req.CompanyDepartmentId;
        data.ContactName = req.ContactName;
        data.WhatsApp = req.WhatsApp;
        data.Email = req.Email;
        data.Remark = req.Remark;
        data.Position = req.Position;

        repo.Update(data);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data);

        var log = SystemAuditLogEntry.Update(Commons.Enums.SystemAuditModule.CompanyStaff, data.StaffId.ToString(), $"Company staff login profile: {data.ContactName}", oldData, data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> DeleteStaff(string staffId)
    {
        var data = await repo.GetByStaffId(staffId);
        Guard.AgainstNullData(data, "Company Communication Contact not found");

        repo.Remove(data!);
        await repo.SaveChangesAsync();
        UpdateCompanyCommunicationContactCache(data!, true);

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyStaff, data!.CompanyId.ToString(), $"Company staff: {data.ContactName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    private void UpdateCompanyCommunicationContactCache(CompanyStaff contact, bool isRemove = false)
    {
        string cacheList = $"{DataCacheKey.Companies}";
        string cacheDetailKey = $"{DataCacheKey.Companies}_{contact.CompanyId}_Details";
        cache.Remove(cacheList);
        cache.Remove(cacheDetailKey);
        //TO DO: update company dto and find index update contact 

    }
}
