using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Services.UploadFile;
using SWSA.MvcPortal.Dtos.Requests.DocumentRecords;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.DocumentRecords;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class DocumentRecordService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
IUploadFileService uploadFileService,
IDocumentRecordRepository repo,
IUserRepository userRepo,
ICompanyDepartmentRepository companyDepartmentRepo,
ISystemAuditLogService sysAuditService
    ) : IDocumentRecordService
{

    public async Task<List<DocumentRecordVM>> GetDocumentRecords()
    {
        var data = userContext.IsSuperAdmin ? [.. await repo.GetAllAsync()] :
            await repo.GetDocumentRecordsByCompanyIds(userContext.AllowedCompanyIds);
        return mapper.Map<List<DocumentRecordVM>>(data);
    }

    public async Task<DocumentRecordVM> GetDocumentRecordById(int id)
    {
        var data = await repo.GetByIdAsync(id);
        Guard.AgainstNullData(data, "DocumentRecord not found");
        Guard.AgainstUnauthorizedCompanyAccess(data!.Department!.CompanyId, data.Department.DepartmentId, userContext);
        return mapper.Map<DocumentRecordVM>(data!);
    }

    public async Task<List<DocumentRecordVM>> GetDocumentRecordByCompanyId(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);

        var data = await repo.GetDocumentRecordsByCompanyId(companyId);
        return mapper.Map<List<DocumentRecordVM>>(data);
    }

    public async Task<List<DocumentRecordVM>> GetDocumentRecordByCompanyDepartmentId(int companyDepartmentId)
    {
        var data = await repo.GetDocumentRecordsByCompanyDepartmentId(companyDepartmentId);
        if (data.Count > 0)
        {
            var firstItem = data.First();
            Guard.AgainstUnauthorizedCompanyAccess(firstItem!.Department!.CompanyId, firstItem.Department.DepartmentId, userContext);
        }

        return mapper.Map<List<DocumentRecordVM>>(data);
    }

    public async Task<bool> CreateDocument(CreateDocumentRecordRequest doc, IFormFile files)
    {
        Guard.AgainstUnauthorizedCompanyAccess(doc.CompanyId, null, userContext);

        var flowType = doc.FlowType.ToString().ToLower();

        var safeCompanyName = uploadFileService.SanitizeFolderName($"{doc.CompanyName}-{doc.CompanyId}");
        var safeDeptName = uploadFileService.SanitizeFolderName($"{doc.DepartmentName}-{doc.CompanyDepartmentId}");
        var subFolder = Path.Combine("docs", safeCompanyName, safeDeptName, flowType);

        var result = await uploadFileService.UploadAsync(files, subFolder, UploadStorageType.Local);
        doc.AttachmentFilePath = result;

        var staff = await userRepo.GetByStaffIdAsync(doc.HandledByStaffId);
        Guard.AgainstNullData(staff, "Staff not found");

        var data = mapper.Map<DocumentRecord>(doc);

        data.HandledByStaffId = staff.Id;

        repo.Add(data);

        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.DocumentRecord, data.Id.ToString(), $"Document: {data.AttachmentFileName}", data);
        sysAuditService.LogInBackground(log);
        return true;
    }

    public async Task<bool> CreateDocuments(CreateDocumentRecordListRequest req, List<IFormFile> files)
    {
        var companyDepartmentIds = req.Documents.Select(d => d.CompanyDepartmentId).Distinct().ToList();
        var companyDepartments = await companyDepartmentRepo.GetByIdsAsync(companyDepartmentIds);

        //Checking if the user has access to the company departments
        foreach (var companyDepartment in companyDepartments)
        {
            Guard.AgainstUnauthorizedCompanyAccess(companyDepartment.CompanyId, companyDepartment.DepartmentId, userContext);
        }

        var staffIds = req.Documents.Select(d => d.HandledByStaffId).Distinct().ToList();
        var staffMap = await userRepo.GetDictionaryByStaffIdsAsync(staffIds);
        var skippedDocuments = new List<string>();

        List<DocumentRecord> records = new List<DocumentRecord>();
        for (int i = 0; i < req.Documents.Count; i++)
        {

            var doc = req.Documents[i];
            if (!staffMap.TryGetValue(doc.HandledByStaffId, out var staff))
            {
                skippedDocuments.Add(doc.AttachmentFileName ?? $"[Index {i}]");
                continue;
            }

            if (i >= files.Count || files[i] == null)
            {
                skippedDocuments.Add(doc.AttachmentFileName ?? $"[Index {i}]");
                continue;
            }

            // Sanitize the folder name
            var flowType = doc.FlowType.ToString().ToLower();
            var safeCompanyName = uploadFileService.SanitizeFolderName($"{doc.CompanyName}-{doc.CompanyId}");
            var safeDeptName = uploadFileService.SanitizeFolderName($"{doc.DepartmentName}-{doc.CompanyDepartmentId}");
            var subFolder = Path.Combine("docs", safeCompanyName, safeDeptName, flowType);

            //Upload the file
            var result = await uploadFileService.UploadAsync(files[i], subFolder, UploadStorageType.Local);
            doc.AttachmentFilePath = result;

            var data = mapper.Map<DocumentRecord>(doc);
            data.HandledByStaffId = staff.Id;

            repo.Add(data);
        }

        await repo.SaveChangesAsync();
        foreach (var doc in records)
        {
            var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.DocumentRecord, doc.Id.ToString(), $"Document: {doc.AttachmentFileName}", doc);
            sysAuditService.LogInBackground(log);
        }
        return true;
    }

    public async Task<DocumentRecordVM> DeleteDocumentById(int docId)
    {
        var doc = await repo.GetByIdAsync(docId);

        Guard.AgainstNullData(doc, "Document not found");
        Guard.AgainstUnauthorizedCompanyAccess(doc!.Department.CompanyId, doc.Department.DepartmentId, userContext);

        repo.Remove(doc!);
        await repo.SaveChangesAsync();

        var filePath = doc!.AttachmentFilePath;
        if (!string.IsNullOrEmpty(filePath))
        {
            await uploadFileService.DeleteAsync(filePath);
        }

        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyOwner, doc.Id.ToString(), $"Document: {doc.AttachmentFileName}", doc);
        sysAuditService.LogInBackground(log);
        return mapper.Map<DocumentRecordVM>(doc);
    }
}
