

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class DocumentRecordService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IDocumentRecordRepository repo
    ) : IDocumentRecordService
{

    public async Task<List<DocumentRecord>> GetDocumentRecords()
    {
        var data = (await repo.GetAllAsync()).ToList();
        return data;
    }

    public async Task<DocumentRecord> GetDocumentRecordById(int id)
    {
        var data = await repo.GetByIdAsync(id);
        Guard.AgainstNullData(data, "DocumentRecord not found");
        return data!;
    }

    public async Task<List<DocumentRecord>> GetDocumentRecordByCompanyId(int companyId)
    {
        var data = await repo.GetDocumentRecordsByCompanyId(companyId);
        return data;
    }

    public async Task<List<DocumentRecord>> GetDocumentRecordByCompanyDepartmentId(int companyDepartmentId)
    {
        var data = await repo.GetDocumentRecordsByCompanyDepartmentId(companyDepartmentId);
        return data;
    }
}
