using SWSA.MvcPortal.Services.Interfaces;
using SWSA.MvcPortal.Repositories.Interfaces;

namespace SWSA.MvcPortal.Services;

// <auto-generated />
public class LLPSubmissionService(
    ILLPSubmissionRepository repo
) : ILLPSubmissionService
{
    #region VM/DTO Query Method 
    #endregion
}