
// <auto-generated />

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Repositories.Repo;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;

public class MsicCodeService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IMsicCodeRepository repo
    ) : IMsicCodeService
{
    public async Task<List<MsicCode>> GetMsicCodeAsync()
    {
        return await GetMsicCodesFromCacheAsync();
    }

    private async Task<List<MsicCode>> GetMsicCodesFromCacheAsync()
    {
        if (cache.TryGetValue(DataCacheKey.MsicCode, out List<MsicCode>? codes))
        {
            return codes ?? [];
        }

        // Fetch data from the database or any other source
        codes = [.. await repo.GetAllAsync()];
        cache.Set(DataCacheKey.Departments, codes, cacheOptions);
        return codes;
    }

}
