

using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using Serilog;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Commons.Helpers;
using SWSA.MvcPortal.Commons.Quartz.Requests;
using SWSA.MvcPortal.Commons.Quartz.Services.Interfaces;
using SWSA.MvcPortal.Dtos.Requests.SchedulerJobs;
using SWSA.MvcPortal.Models.ScheduledJobs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class ScheduledJobService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
IScheduledJobRepository repo,
IJobSchedulerService schedulerService
    ) : IScheduledJobService
{
    public async Task<List<ScheduledJobVM>> GetAllScheduledJobs()
    {
        var data = await repo.GetAllAsync();
        return mapper.Map<List<ScheduledJobVM>>(data);
    }

    public async Task<ScheduledJobVM> GetScheduledJobByJobKey(string jobKey)
    {
        var data = await repo.GetScheduledByJobKeyAsync(jobKey);
        return mapper.Map<ScheduledJobVM>(data);
    }

    public async Task<bool> ScheduleJob(ScheduleJobRequest req)
    {
        var data = await repo.GetScheduledByJobKeyAsync(req.JobKey);
        Guard.AgainstNullData(data, "Job Not Found");

        if (req.ExecuteNow)
        {
            var executeRequest = new BaseJobRequest()
            {
                StartTime = DateTime.Now,
            };
            await schedulerService.ScheduleJob(executeRequest, data.JobType);
            data.LastExecuteAt = DateTime.Now;
        }
        string cronExpression = CronExpressionBuilder.BuildCronExpression(req);

        data.IsEnabled = req.IsEnabled;
        data.ScheduleType = req.ScheduleType;
        data.CronExpression = cronExpression;
        data.UpdatedAt = DateTime.Now;
        data.TriggerTime = req.ScheduleType == ScheduleType.Once ? req.TriggerTime : null;

        var request = new BaseJobRequest()
        {
            StartTime = req.ScheduleType == ScheduleType.Once ? req.TriggerTime : null,
            CronExpression = cronExpression,
            IsCustom = data.IsCustom
        };

        repo.Update(data);
        await repo.SaveChangesAsync();

        await schedulerService.ClearSpecificJobByKey(req.JobKey);
        if (data.IsEnabled)
        {
            await schedulerService.ScheduleJob(request, data.JobType);
        }

        return true;
    }

    public async Task<bool> ExecuteByJobKey(string jobKey)
    {
        var data = await repo.GetScheduledByJobKeyAsync(jobKey);
        Guard.AgainstNullData(data, "Job Not Found");

        var request = new BaseJobRequest()
        {
            StartTime = DateTime.Now,
        };
        await schedulerService.ScheduleJob(request, data.JobType);

        data.LastExecuteAt = DateTime.Now;
        repo.Update(data);
        await repo.SaveChangesAsync();

        return true;
    }

    public async Task UpdateExecuteTimeAsync(string jobkey)
    {
        var job = await repo.GetScheduledByJobKeyAsync(jobkey);
        if (job == null)
        {
            Log.Error($"[Job] job key not found, update failed :{jobkey}");
            return;
        }

        job.LastExecuteAt = DateTime.Now;
        repo.Update(job);
        await repo.SaveChangesAsync();
    }

}
