using Newtonsoft.Json;
using SWSA.MvcPortal.Commons.Extensions;
using SWSA.MvcPortal.Commons.Filters;
using SWSA.MvcPortal.Commons.Services.BackgroundQueue;
using SWSA.MvcPortal.Commons.Services.SystemAuditLog;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class SystemAuditLogService(
IUserContext userContext,
IServiceProvider serviceProvider,
IBackgroundTaskQueue queue
    ) : ISystemAuditLogService
{

    public void LogInBackground(SystemAuditLogEntry entry)
    {
        queue.Queue(async token =>
        {
            using var scope = serviceProvider.CreateScope();
            var repo = scope.ServiceProvider.GetRequiredService<ISystemAuditLogRepository>();

            var url = AuditNavigationService.GenerateUrl(entry.Module, entry.EntityId);
            var log = new SystemAuditLog
            {
                Module = entry.Module.ToString(),
                ActionType = entry.ActionType.ToString(),
                EntityId = entry.EntityId,
                EntityName = entry.EntityName,
                NavigateUrl = url,
                ChangeSummaryJson = BuildChangeSummary(entry.OldData, entry.NewData),
                PerformedBy = userContext.Name,
                PerformedByCompanyStaffId = userContext.IsCompanyStaff ? userContext.EntityId : null,
                PerformedByUserId = !userContext.IsCompanyStaff ? userContext.EntityId : null,
                CompanyId = userContext.IsCompanyStaff ? userContext.CompanyId : null,
                PerformedAt = DateTime.Now
            };
            repo.Add(log);
            await repo.SaveChangesAsync();
        });
    }

    private string? BuildChangeSummary(object? oldVal, object? newVal)
    {
        if (oldVal == null || newVal == null) return null;

        var dict = new Dictionary<string, string[]>();
        var props = oldVal.GetType().GetProperties();

        foreach (var prop in props)
        {
            var auditAttr = prop.GetCustomAttribute<SystemAuditLogAttribute>();
            if (auditAttr == null) continue;

            var displayName = auditAttr.Name;
            var oldValue = prop.GetValue(oldVal);
            var newValue = prop.GetValue(newVal);

            var oldStr = ConvertToDisplayString(oldValue);
            var newStr = ConvertToDisplayString(newValue);

            if (oldStr != newStr)
                dict[displayName] = new[] { oldStr ?? "", newStr ?? "" };
        }

        return dict.Count > 0 ? JsonConvert.SerializeObject(dict) : null;
    }


    private string? ConvertToDisplayString(object? value)
    {
        if (value == null) return null;

        if (value is Enum e)
            return e.GetDisplayName();

        return value.ToString();
    }
}
