using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class WorkAssignmentAccountMonthService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
IWorkAssignmentAccountMonthRepository repo
    ) : IWorkAssignmentAccountMonthService
{

}
