using System.Net.WebSockets;
using AutoMapper;
using Microsoft.Extensions.Caching.Memory;
using SWSA.MvcPortal.Commons.Constants;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces;

namespace SWSA.MvcPortal.Services;
// <auto-generated />
public class WorkAssignmentUserMappingService(
IMemoryCache cache,
MemoryCacheEntryOptions cacheOptions,
IMapper mapper,
IUserContext userContext,
ISystemAuditLogService sysAuditService,
IWorkAssignmentUserMappingRepository repo,
IUserRepository userRepo
    ) : IWorkAssignmentUserMappingService
{
    public async Task<int> AddUser(WorkUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        if (req.Department != DepartmentType.Account && req.Department != DepartmentType.Audit)
            throw new BadHttpRequestException($"Invalid department: {req.Department}");

        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");

        var mapUser = await repo.GetByUserIdAsync(req.TaskId, user.Id, req.Department);
        if (mapUser != null)
            throw new BadHttpRequestException($"User already exists in work assignment");

        var entity = new WorkAssignmentUserMapping()
        {
            Department = req.Department,
            UserId = user.Id,
            WorkAssignmentId = req.TaskId,
        };

        repo.Add(entity);
        await repo.SaveChangesAsync();
        var log = SystemAuditLogEntry.Create(Commons.Enums.SystemAuditModule.CompanyWorkAssignment,
            user.StaffId.ToString(), $"Assign {req.Department} work to User: {user.FullName}", mapUser!);
        sysAuditService.LogInBackground(log);

        return entity.Id;
    }

    public async Task<bool> RemoveUser(WorkUserRequest req)
    {
        Guard.AgainstNotSuperAdmin(userContext);

        if (req.Department != DepartmentType.Account && req.Department != DepartmentType.Audit)
            throw new BadHttpRequestException($"Invalid department: {req.Department}");

        var user = await userRepo.GetByStaffIdAsync(req.StaffId);
        Guard.AgainstNullData(user, "User not found");

        var mapUser = await repo.GetByUserIdAsync(req.TaskId, user.Id, req.Department);
        Guard.AgainstNullData(mapUser, "User not found in work assignment");

        repo.Remove(mapUser!);
        await repo.SaveChangesAsync();
        var log = SystemAuditLogEntry.Delete(Commons.Enums.SystemAuditModule.CompanyWorkAssignment,
            user.StaffId.ToString(), $"Remove User: {user.FullName} from {req.Department} work", mapUser!);
        sysAuditService.LogInBackground(log);

        return true;
    }
}
