using AutoMapper;
using Force.DeepCloner;
using SWSA.MvcPortal.Commons.Enums;
using SWSA.MvcPortal.Commons.Guards;
using SWSA.MvcPortal.Dtos.Requests.Submission;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;
using SWSA.MvcPortal.Models.SystemAuditLogs;
using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces.Submission;
using SWSA.MvcPortal.Services.Interfaces.SystemCore;
using SWSA.MvcPortal.Services.Interfaces.SystemInfra;

namespace SWSA.MvcPortal.Services.Submission;

// <auto-generated />
public class AnnualReturnSubmissionService(
    IAnnualReturnSubmissionRepository repo,
    IMapper mapper,
    IUserContext userContext,
    ISystemAuditLogService sysAnnualReturnService,
    ICompanyRepository companyRepo,
    ICompanyWorkAssignmentRepository workAssignmentRepo
) : IAnnualReturnSubmissionService
{
    #region VM/DTO Query Method 
    public async Task<List<AnnualReturnSubmissionVM>> GetARSubmissionVMsAsync()
    {
        var data = await repo.GetListVMAsync();
        //For download /view link 
        return mapper.Map<List<AnnualReturnSubmissionVM>>(data);
    }

    public async Task<AnnualReturnSubmissionVM> GetARSubmissionVMByIdAsync(int submissionId)
    {
        var data = await repo.GetVMByIdAsync(submissionId);
        Guard.AgainstUnauthorizedCompanyAccess(data.GetCompanyId(), null, userContext);
        //For download /view link 

        return mapper.Map<AnnualReturnSubmissionVM>(data);
    }
    #endregion

    public async Task<int> RequestSubmissionForCompany(int companyId)
    {
        Guard.AgainstUnauthorizedCompanyAccess(companyId, null, userContext);
        var cp = await companyRepo.GetWithIncludedByIdAsync(companyId);
        Guard.AgainstNullData(cp, "Company not found");

        var entity = new AnnualReturnSubmission()
        {
            Remarks = "Request for Annual Return submission",
        };

        entity.SetAnniversaryAndTargetedARDate(cp);

        List<WorkAssignmentUserMapping> assignedUser = userContext.IsSuperAdmin
            ? [..cp!.UserCompanyDepartments.Select(c => c.UserId).Distinct()
            .Select(c=> new WorkAssignmentUserMapping {
                UserId = c
            })] //Super admin assign to all handle user
                : [new WorkAssignmentUserMapping {
            UserId = userContext.EntityId,
          }]; //System user assign to self

        var task = new CompanyWorkAssignment
        {
            CompanyId = companyId,
            WorkType = WorkType.AnnualReturn,
            ServiceScope = ServiceScope.Other,
            CompanyActivityLevel = cp.CompanyActivityLevel,
            CompanyStatus = cp.CompanyStatus,
            ARSubmission = entity,
            InternalNote = "Request for Annual Return submission",
            IsYearEndTask = false,
            AssignedUsers = assignedUser,
            Progress = new CompanyWorkProgress(),
        };

        workAssignmentRepo.Add(task);
        await repo.SaveChangesAsync();

        var log = SystemAuditLogEntry.Create(SystemAuditModule.Company, companyId.ToString(), $"Requested {cp.Name} Annual Return submission", entity);
        sysAnnualReturnService.LogInBackground(log);
        return entity.Id;
    }


    public async Task<bool> UpdateSubmissionForCompany(EditARSubmissionRequest req)
    {
        Guard.AgainstUnauthorizedCompanyAccess(req.CompanyId, null, userContext);
        var data = await repo.GetByIdAsync(req.SubmissionId);
        Guard.AgainstNullData(data, "Submission not found");
        var task = await workAssignmentRepo.GetUpdateVMById(data!.WorkAssignmentId);
        Guard.AgainstNullData(task, "Task not found");
        var cp = await companyRepo.GetByIdAsync(req.CompanyId);
        Guard.AgainstNullData(cp, "Company not found");

        var oldData = data!.DeepClone();

        UpdateSubmissionFields(data, req);
        UpdateWorkAssignmentProgress(task, data);

        workAssignmentRepo.Update(task!);
        repo.Update(data);
        await repo.SaveChangesAsync();
        var log = SystemAuditLogEntry.Update(SystemAuditModule.Company, req.CompanyId.ToString(), $"Updated {cp.Name} Annual Return submission", oldData, data);
        sysAnnualReturnService.LogInBackground(log);
        return true;
    }

    private void UpdateSubmissionFields(AnnualReturnSubmission data, EditARSubmissionRequest req)
    {
        data.AnniversaryDate = req.AnniversaryDate;
        data.ARDueDate = req.ARDueDate;
        data.TargetedARDate = req.TargetedARDate;
        data.DateOfAnnualReturn = req.DateOfAnnualReturn;
        data.DateSubmitted = req.DateSubmitted;
        data.DateSentToClient = req.DateSentToClient;
        data.DateReturnedByClient = req.DateReturnedByClient;
        data.Remarks = req.Remarks;
    }

    private void UpdateWorkAssignmentProgress(CompanyWorkAssignment task, AnnualReturnSubmission data)
    {
        if (task.Progress != null && task.Progress.Status == WorkProgressStatus.Pending)
        {
            //Some business logic checking for task complete
            if (data.IsSubmissionComplete())
            {
                task.Progress.Complete();
            }
            else
            {
                task.Progress.Processing();
            }
        }
    }
}