using SWSA.MvcPortal.Repositories.Interfaces;
using SWSA.MvcPortal.Services.Interfaces.Submission;

namespace SWSA.MvcPortal.Services.Submission;

// <auto-generated />
public class AuditSubmissionService(
    IAuditSubmissionRepository repo
) : IAuditSubmissionService
{
    #region VM/DTO Query Method 
    #endregion
}