
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;

// <auto-generated />
public interface ICompanyDepartmentService
{
    // Define your method here
    Task<List<CompanyDepartment>> GetByCompanyId(int companyId);
}
