using SWSA.MvcPortal.Dtos.Requests.CompanyStrikeOffSubmissions;
using SWSA.MvcPortal.Models.CompanyStrikeOffSubmission;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface ICompanyStrikeOffSubmissionService
{
    Task<bool> DeleteSubmissionById(int submissionId);
    Task<CompanyStrikeOffSubmissionVM> GetStrikeOffSubmissionVMByIdAsync(int submissionId);

    // Define your method here
    Task<List<CompanyStrikeOffSubmissionVM>> GetStrikeOffSubmissionVMsAsync();
    Task<int> RequestSubmissionForCompany(int companyId);
    Task<bool> UpdateSubmissionForCompany(EditCompanyStrikeOffSubmissionRequest req);
}
