

using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    // Define your method here
    Task<List<CompanyWorkAssignment>> GetWorkAssignments();
}
