

using SWSA.MvcPortal.Dtos.Requests.CompanyWorks;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.CompnayWorks;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface ICompanyWorkAssignmentService
{
    Task<int> CreateCompanyWorkAssignment(CreateCompanyWorkAssignmentRequest req);
    Task<CompanyWorkAssignment> DeleteWork(int taskId);
    Task<bool> EditCompanyWorkAssignment(EditCompanyWorkAssignmentRequest req);
    Task<CompanyWorkVM> GetWorkAssignmentById(int taskId);

    // Define your method here
    Task<List<CompanyWorkListVM>> GetWorkAssignments();
}
