// <auto-generated />

using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;

public interface ICompanyTypeService
{
    // Define your method here
    Task<List<CompanyType>> GetCompanyTypesAsync();
}
