// <auto-generated />
using Microsoft.AspNetCore.Components.Forms;
using SWSA.MvcPortal.Dtos.Requests.Companies;

namespace SWSA.MvcPortal.Services.Interfaces;

public interface ICompanyOfficialContactService
{
    // Define your method here
    Task<int> CreateContact(CreateCompanyOfficialContactRequest req);
    Task<bool> EditContact(EditCompanyOfficialContactRequest req);
    Task<bool> DeleteContact(int ownerId);
}
