
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />

public interface IDepartmentService
{
    // Define your method here
    Task<List<Department>> GetDepartments();
}
