using SWSA.MvcPortal.Models.ScheduledJobs;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface IScheduledJobService
{
    Task<List<ScheduledJobVM>> GetAllScheduledJobs();

    // Define your method here
    Task UpdateExecuteTimeAsync(string jobkey);
}
