using SWSA.MvcPortal.Dtos.Requests.SchedulerJobs;
using SWSA.MvcPortal.Models.ScheduledJobs;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface IScheduledJobService
{
    Task<bool> ExecuteByJobKey(string jobKey);
    Task<List<ScheduledJobVM>> GetAllScheduledJobs();
    Task<ScheduledJobVM> GetScheduledJobByJobKey(string jobKey);

    Task<bool> ScheduleJob(ScheduleJobRequest req);

    // Define your method here
    Task UpdateExecuteTimeAsync(string jobkey);
}
