
using SWSA.MvcPortal.Models.SystemAuditLogs;

namespace SWSA.MvcPortal.Services.Interfaces;
// <auto-generated />
public interface ISystemAuditLogService
{
    // Define your method here
    void LogInBackground(SystemAuditLogEntry entry);
}
