using Mapster;
using SWSA.MvcPortal.Entities.Contacts;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.CompanyProfile;

// <auto-generated />
public class CompanyOwnerMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CompanyOwner, CompanyOwner>();
    }
}
        