using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.CompanyProfile;

// <auto-generated />
public class CompanyCommunicationContactMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<CommunicationContact, CommunicationContact>();
    }
}
        