using Mapster;
using SWSA.MvcPortal.Entities;
using SWSA.MvcPortal.Models.Submissions;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.Submission;

// <auto-generated />
public class AnnualReturnSubmissionMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<AnnualReturnSubmission, AnnualReturnSubmission>();
        config.ForType<AnnualReturnSubmission, AnnualReturnSubmissionVM>()
            .Map(dest => dest.SubmissionId, src => src.Id);
    }
}
        