using Mapster;
using SWSA.MvcPortal.Entities;

namespace SWSA.MvcPortal.Commons.MapsterConfigs.Submission;

// <auto-generated />
public class LLPSubmissionMapsterConfig : IMapsterConfig
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<LLPSubmission, LLPSubmission>();
    }
}
        